# Intelligent Task Offloading in 5G Heterogeneous Edge-Fog-Cloud Environments
## LSH-GRL: Reproducible Single-Notebook Implementation

**Research scholar:** Poonam Arjun Undre (PRN 23079001137) · **Guide:** Dr. Kanhaiya Sharma
Symbiosis Institute of Technology, Symbiosis International (Deemed University)

---

### What this notebook is

A complete, self-contained re-implementation. Every number in every table and figure is
computed by a cell above it. **No metric is hardcoded anywhere.**

### Objective mapping (from the research proposal)

| Proposal objective | Where it is addressed | Evidence produced |
|---|---|---|
| **O1.** Adaptive offloading algorithm for efficient clustering | §4 | LSH retrieval recall + query-time speedup vs exhaustive search |
| **O2.** System for dynamic, context-aware offloading decisions | §5–§7 | Graph-RL agent with per-node scoring, held-out evaluation |
| **O3.** Optimise allocation for latency, energy, resource utilisation | §2, §3 | Four-term reward; oracle headroom analysis |
| **O4.** Test/validate vs baselines under varying conditions | §6–§9 | 7 baselines, ablation, multi-seed statistics, mobility sweep |

### Two mandatory gates

The notebook **stops** if either fails. This is deliberate.

1. **Gate 1 (§2)** — physics sanity. If cloud is not slower than edge, or if nothing ever
   misses a deadline, the simulated world does not contain the research problem.
2. **Gate 2 (§3)** — headroom. If the best simple heuristic is already within 5% of the
   oracle, there is nothing for a learning method to contribute, and no result obtained
   downstream would be meaningful.

### Runtime
~20–30 min on a Colab CPU runtime with `PROFILE = "full"`. Set `PROFILE = "quick"` (~8 min)
for a smoke test.

## §0 — Configuration and seed control

All constants live here. `set_seed()` is the **only** place the RNG is seeded: constructors
never reset it, so multi-seed runs in §9 are genuinely independent.

In [1]:
# Colab: torch is preinstalled. If running elsewhere and this fails:
#   !pip install torch pandas numpy matplotlib scipy scikit-learn openpyxl
import torch, scipy, matplotlib
print("torch", torch.__version__, "| scipy", scipy.__version__)

torch 2.11.0+cu128 | scipy 1.16.3

In [2]:
# ===== SECTION 0: CONFIG =====
import os, sys, json, time, math, random, warnings
import numpy as np, pandas as pd
warnings.filterwarnings("ignore")

# ---- POINT THIS AT YOUR dataset/ FOLDER -------------------------------------
# Colab example:
from google.colab import drive; drive.mount('/content/drive')
DATA_DIR = '/content/drive/MyDrive/CS MEMBERS/IMPLEMENTATION/ATHARAV KAMBLE/5G/dataset'
# DATA_DIR = os.environ.get("LSHGRL_DATA", "./dataset")
OUT_DIR  = "./results_V4"
DRIVE_OUT = "/content/drive/MyDrive/CS MEMBERS/IMPLEMENTATION/ATHARAV KAMBLE/5G/results_V4"   # <-- your Drive folder
os.makedirs(OUT_DIR, exist_ok=True)

PROFILE = "full"        # "full" or "quick"
P = {
 "quick": dict(N_TASKS=4000, EPISODES=12, EP_LEN=200, SEEDS=[0,1,2], EVAL_EVERY=3),
 "full":  dict(N_TASKS=8000, EPISODES=25, EP_LEN=250, SEEDS=list(range(10)), EVAL_EVERY=5),
}[PROFILE]

NUM_EDGE, NUM_FOG, NUM_CLOUD = 10, 5, 3
N_NODES = 1 + NUM_EDGE + NUM_FOG + NUM_CLOUD   # index 0 = LOCAL device
LOCAL, EDGE, FOG, CLOUD = 0, 1, 2, 3
TIER = np.array([LOCAL] + [EDGE]*NUM_EDGE + [FOG]*NUM_FOG + [CLOUD]*NUM_CLOUD)

BANDWIDTH_HZ = 100e6
SNR_DB_BY_MOBILITY = {"static":25.0, "low":18.0, "medium":11.0, "high":5.0}
BACKHAUL_BPS = {LOCAL:np.inf, EDGE:10e9, FOG:5e9, CLOUD:1e9}
P_TX_W, P_IDLE_W = 0.6, 0.40      # 0.40 W = 5G NR RRC-connected modem draw while waiting
KAPPA_DEVICE = 1e-9            # Joules per device CPU cycle
E_REF_J = 0.5                  # energy normalisation reference
W_SUCCESS, W_LAT, W_ENERGY, W_COST = 0.35, 0.15, 0.15, 0.35
# Resource price per tier (proposal Research Gap #2: latency-vs-energy AND bandwidth-vs-cost).
# Edge is cheap and scarce, cloud is expensive and abundant.
PRICE_CYCLE = {LOCAL:0.0, EDGE:1.0e-11, FOG:3.0e-11, CLOUD:1.0e-10}
PRICE_BIT   = {LOCAL:0.0, EDGE:1.0e-11, FOG:4.0e-11, CLOUD:1.5e-10}
RESULT_RATIO = 0.05

CAP_RANGE = {LOCAL:(2e9,2e9), EDGE:(6e9,14e9), FOG:(35e9,65e9), CLOUD:(150e9,250e9)}
PROP_RANGE = {LOCAL:(0.0,0.0), EDGE:(2.0,6.0), FOG:(12.0,22.0), CLOUD:(40.0,70.0)}

STRICT_DATA = True             # abort rather than silently use synthetic data
TARGET_LOCAL_MEDIAN_MS = 250.0 # calibrate workload intensity to the device class
TARGET_ORACLE_MISS = 0.06
TARGET_EDGE_UTIL   = 0.90


def set_seed(s):
    random.seed(s); np.random.seed(s)
    try:
        import torch; torch.manual_seed(s)
    except Exception: pass



PLOTS_DIR = os.path.join(OUT_DIR, "plots"); os.makedirs(PLOTS_DIR, exist_ok=True)
PLOT_DPI, PLOT_FIGSIZE = 1000, (8, 5)
COLORS = {"lsh_grl_hpfoo":"#0D47A1","lsh_grl":"#1565C0","grl":"#EF6C00","no_graph":"#8D6E63",
          "dqn":"#2E7D32","greedy":"#6A1B9A",
          "random":"#C62828","local_only":"#5D4037","all_cloud":"#455A64","oracle":"#000000"}
LABELS = {"lsh_grl_hpfoo":"LSH-GRL-HPFOO (Proposed)","lsh_grl":"LSH-GRL (no HPFOO)",
          "grl":"GRL only","no_graph":"No-graph scoring","dqn":"Standard DQN",
          "greedy":"Greedy (min-latency)","random":"Random Offloading",
          "local_only":"Local-Only","all_cloud":"All-to-Cloud","oracle":"Myopic Oracle (bound)"}
# ---- Requirement 2: Pufferfish perturbation-radius schedule ---------------------
# "legacy"   : (ub-lb)/t with t monotonic across the whole run (v3 behaviour).
#              t never resets, so the coarse global step is never actually taken
#              and the radius has collapsed to ~0.04 by late training.
# "reset"    : (ub-lb)/tau with tau = 1..iters, reset every invocation. This is the
#              schedule the Clarifications document describes.
# "annealed" : (ub-lb)/tau * 1/sqrt(1+k), k = invocation index. Restores the coarse-
#              to-fine contraction WITHIN each invocation while still annealing the
#              overall radius as training proceeds. DEFAULT.
PUFFERFISH_SCHEDULE = "legacy"

RESULTS = {}
print("profile:", PROFILE, P)
print("pufferfish schedule:", PUFFERFISH_SCHEDULE)

Mounted at /content/drive
profile: full {'N_TASKS': 8000, 'EPISODES': 25, 'EP_LEN': 250, 'SEEDS': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'EVAL_EVERY': 5}
pufferfish schedule: legacy

## §1 — Data harmonisation

Four real traces are mapped into one task schema. Trace fields do not map one-to-one onto a
task model, so the conversions below are **stated modelling assumptions**, not measurements.
If a file is missing, a clearly-labelled synthetic substitute is used and reported — it is
never silently swapped in.

In [3]:
# ===== SECTION 1: DATA HARMONISATION =====
MOB_IDX = {"static":0.05, "low":0.2, "medium":0.45, "high":0.8}

def _load_task_offloading(n):
    p = os.path.join(DATA_DIR, "task_offloading_dataset.csv")
    df = pd.read_csv(p).sample(n=min(n,10**7), random_state=42)
    traf = (pd.to_numeric(df["Downlink_Traffic"], errors="coerce").fillna(0) +
            pd.to_numeric(df["Uplink_Traffic"], errors="coerce").fillna(0))
    dur = pd.to_numeric(df["Duration"], errors="coerce").fillna(1).clip(1, 600)
    return pd.DataFrame({
        "cpu_cycles": (traf*2.0e4 + dur*3.0e7).clip(5e6, 3e9),
        "data_size_bytes": (traf*1024.0).clip(1e3, 2e7),
        "mobility_index": 0.45,
        "priority": pd.to_numeric(df["RAT"], errors="coerce").fillna(1)*50,
        "source": "task_offloading"})

def _load_vec(n):
    p = os.path.join(DATA_DIR, "VEC_edge_data.csv")
    df = pd.read_csv(p).sample(n=min(n,10**7), random_state=42)
    ex = pd.to_numeric(df["execution_time"], errors="coerce").fillna(50).clip(1, 2000)
    return pd.DataFrame({
        "cpu_cycles": (ex*1e-3*2e9).clip(5e6, 3e9),
        "data_size_bytes": (ex*2.0e3).clip(1e3, 2e7),
        "mobility_index": df["device_mobility_status"].map(MOB_IDX).fillna(0.45).values,
        "priority": 100.0,
        "source": "vec_edge"})

def _load_azure(n):
    p = os.path.join(DATA_DIR, "New folder", "AzureLLMInferenceTrace_conv.csv")
    df = pd.read_csv(p).sample(n=min(n,10**7), random_state=42)
    ct = pd.to_numeric(df["ContextTokens"], errors="coerce").fillna(500)
    gt = pd.to_numeric(df["GeneratedTokens"], errors="coerce").fillna(100)
    return pd.DataFrame({
        "cpu_cycles": ((ct+gt)*5.0e4).clip(5e6, 3e9),
        "data_size_bytes": (ct*4.0).clip(1e3, 2e7),
        "mobility_index": 0.05,
        "priority": 150.0,
        "source": "azure_llm"})

def _load_borg(n):
    p = os.path.join(DATA_DIR, "borg_traces_data.csv")
    df = pd.read_csv(p, usecols=["start_time","end_time","priority","assigned_memory"],
                     nrows=120000)
    st = pd.to_numeric(df["start_time"], errors="coerce")
    et = pd.to_numeric(df["end_time"], errors="coerce")
    dur_us = (et-st).abs()
    df = df.assign(dur=dur_us).dropna(subset=["dur"])
    df = df[(df["dur"] > 0)].sample(n=min(n, len(df)), random_state=42)
    mem = pd.to_numeric(df["assigned_memory"], errors="coerce").fillna(0.001)
    return pd.DataFrame({
        "cpu_cycles": (df["dur"].values/1e6*5e8).clip(5e6, 3e9),
        "data_size_bytes": (mem.values*1e8).clip(1e3, 2e7),
        "mobility_index": 0.05,
        "priority": pd.to_numeric(df["priority"], errors="coerce").fillna(100).values,
        "source": "borg"})

def _synthetic(n, tag="synthetic"):
    rng = np.random.RandomState(42)
    return pd.DataFrame({
        "cpu_cycles": np.exp(rng.uniform(np.log(5e6), np.log(3e9), n)),
        "data_size_bytes": np.exp(rng.uniform(np.log(1e3), np.log(2e7), n)),
        "mobility_index": rng.choice(list(MOB_IDX.values()), n),
        "priority": rng.uniform(50,300,n), "source": tag})

def harmonize(n_total, verbose=True):
    per = n_total // 4
    frames, log = [], []
    for name, fn in [("task_offloading",_load_task_offloading), ("vec_edge",_load_vec),
                     ("azure_llm",_load_azure), ("borg",_load_borg)]:
        try:
            f = fn(per); frames.append(f); log.append((name, len(f), "loaded"))
        except Exception as e:
            if STRICT_DATA:
                raise FileNotFoundError(
                    "Loader '%s' failed: %s\nDATA_DIR is %r (absolute: %s).\nFix the path: "
                    "synthetic substitutes would make every downstream result meaningless."
                    % (name, e, DATA_DIR, os.path.abspath(DATA_DIR))) from e
            f = _synthetic(per, name+"_synth"); frames.append(f)
            log.append((name, len(f), "SYNTHETIC fallback: %s" % str(e)[:60]))
    df = pd.concat(frames, ignore_index=True)
    rng = np.random.RandomState(42)
    df["mobility_index"] = df["mobility_index"].astype(float)
    # latency budget (deadline) is a workload parameter, calibrated in Section 2
    df["deadline_raw_ms"] = rng.uniform(30, 400, len(df))
    df = df.sample(frac=1.0, random_state=42).reset_index(drop=True)
    df["task_id"] = np.arange(len(df))
    if STRICT_DATA:
        bad = [n for n, _, s in log if s != "loaded"]
        assert not bad, "Synthetic fallback used for: %s" % bad
    if verbose:
        print("Harmonisation report")
        for nme, k, st in log: print("  %-16s %6d  %s" % (nme, k, st))
        print("  TOTAL %d tasks" % len(df))
    return df, log


def load_site_topology(n_sites=30):
    try:
        s = pd.read_csv(os.path.join(DATA_DIR,"New folder","site.csv"),
                        usecols=["SITE_ID","LATITUDE","LONGITUDE"]).dropna()
        s = s.sample(n=n_sites, random_state=42)
        return s[["LATITUDE","LONGITUDE"]].values
    except Exception:
        return None

In [4]:
df, load_log = harmonize(P["N_TASKS"])
sites = load_site_topology(30)
print("\nreal site topology:", "loaded %d sites" % len(sites) if sites is not None else "unavailable")

# Bimodal deadline mix: 30% latency-critical (URLLC-like), 70% relaxed (eMBB-like).
_rng = np.random.RandomState(7); _n = len(df)
_urgent = _rng.random(_n) < 0.30
df["deadline_raw_ms"] = np.where(_urgent, _rng.uniform(15, 60, _n), _rng.uniform(150, 600, _n))
df["urgent"] = _urgent
print("urgent (tight-deadline) share: %.1f%%" % (100*_urgent.mean()))

# Compute-intensity calibration: trace-to-cycles mappings are modelling assumptions,
# so absolute compute demand depends on which traces loaded. Scale once so the median
# task is a genuine load on the modelled 2 GIPS device class. Reported, not hidden.
_med_local_ms = df["cpu_cycles"].median() / CAP_RANGE[LOCAL][0] * 1000
CPU_SCALE = TARGET_LOCAL_MEDIAN_MS / _med_local_ms
df["cpu_cycles"] = (df["cpu_cycles"] * CPU_SCALE).clip(5e6, 1e10)
print("compute-intensity scale : %.2fx  (median local exec %.0f -> %.0f ms)"
      % (CPU_SCALE, _med_local_ms, TARGET_LOCAL_MEDIAN_MS))
assert sites is not None, "site.csv did not load - edge propagation loses real-topology grounding."
display(df[["cpu_cycles","data_size_bytes","deadline_raw_ms","mobility_index","source"]].describe().T)

Harmonisation report
  task_offloading    2000  loaded
  vec_edge           2000  loaded
  azure_llm          2000  loaded
  borg               2000  loaded
  TOTAL 8000 tasks

real site topology: loaded 30 sites
urgent (tight-deadline) share: 30.5%
compute-intensity scale : 1.10x  (median local exec 228 -> 250 ms)

,count,mean,std,min,25%,50%,75%,max
cpu_cycles,8000.0,1.124282e+09,1.269811e+09,5.866228e+06,7.711623e+07,5.000000e+08,1.971552e+09,3.289474e+09
data_size_bytes,8000.0,1.183399e+06,2.995885e+06,1.000000e+03,4.783000e+03,3.072000e+05,1.101685e+06,2.000000e+07
deadline_raw_ms,8000.0,2.710469e+02,1.894780e+02,1.500098e+01,5.125768e+01,2.731104e+02,4.381534e+02,5.998507e+02
mobility_index,8000.0,2.330312e-01,2.334091e-01,5.000000e-02,5.000000e-02,5.000000e-02,4.500000e-01,8.000000e-01

## §2 — Environment model and **Gate 1**

Latency = uplink (Shannon) + backhaul serialisation + **propagation RTT** + queueing + compute + downlink.

The propagation RTT term is the one that was missing from the original code. Without it,
edge and cloud cost the same to reach and "offload everything to the largest server" is
optimal by construction — which inverts the premise of edge computing.

Energy is **device** energy (radio TX + RRC-connected idle, or local CPU), not server energy.

Reward has four terms, matching Research Gap #2 of the proposal (*latency vs energy*,
*bandwidth vs cost*):

$$r = w_s\,\mathbb{1}[\ell \le D] + w_l\Big(1-\tfrac{\ell}{D}\Big)^+ + w_e\Big(1-\tfrac{E}{E_{local}}\Big)^+ + w_c\Big(1-\tfrac{c}{c_{cloud}}\Big)^+$$

In [5]:
# ===== SECTION 2: ENVIRONMENT =====
class OffloadingEnv:
    # 19 actions: 0 = local device, 1..10 edge, 11..15 fog, 16..18 cloud.
    # Latency = uplink + backhaul + propagation RTT + queueing + compute + downlink.
    # Energy is DEVICE energy: radio TX power * uplink time + idle power * wait,
    # or local CPU energy if executed on device.
    def __init__(self, seed=0, sites=None, deadline_scale=1.0, arrival_scale=1.0):
        rng = np.random.RandomState(seed)
        self.rng = rng
        self.cap = np.zeros(N_NODES); self.prop = np.zeros(N_NODES)
        for i in range(N_NODES):
            lo,hi = CAP_RANGE[TIER[i]];  self.cap[i]  = rng.uniform(lo,hi)
            lo,hi = PROP_RANGE[TIER[i]]; self.prop[i] = rng.uniform(lo,hi)
        if sites is not None and len(sites) >= NUM_EDGE:
            pts = sites[rng.choice(len(sites), NUM_EDGE, replace=False)]
            c = pts.mean(0); d = np.linalg.norm(pts-c, axis=1)
            d = (d-d.min())/(np.ptp(d)+1e-9)
            self.prop[1:1+NUM_EDGE] = 2.0 + 4.0*d      # real site spread -> RTT spread
            self.site_coords = pts
        else:
            self.site_coords = None
        self.backhaul = np.array([BACKHAUL_BPS[TIER[i]] for i in range(N_NODES)])
        self.deadline_scale = deadline_scale
        self.arrival_scale  = arrival_scale
        self.adj = self._build_adj()
        self.reset()

    def _build_adj(self):
        A = np.zeros((N_NODES, N_NODES))
        e0, f0, c0 = 1, 1+NUM_EDGE, 1+NUM_EDGE+NUM_FOG
        for i in range(e0, f0): A[0,i]=A[i,0]=1                    # device <-> edge
        for i in range(e0,f0):
            for j in range(i+1,f0):
                if self.rng.random() < 0.4: A[i,j]=A[j,i]=1        # edge mesh
        for k,i in enumerate(range(e0,f0)):
            j = f0 + (k % NUM_FOG); A[i,j]=A[j,i]=1                # edge -> fog
        for i in range(f0,c0):
            for j in range(c0,N_NODES): A[i,j]=A[j,i]=1            # fog -> cloud
        A += np.eye(N_NODES)
        return (A>0).astype(np.float32)

    def reset(self):
        self.backlog = np.zeros(N_NODES)   # queued cycles per node
        self.nserved = np.zeros(N_NODES)
        self.t_ms = 0.0

    def advance_to(self, t_ms):
        dt = max(0.0, t_ms - self.t_ms)
        self.backlog = np.maximum(0.0, self.backlog - self.cap*dt/1000.0)
        self.t_ms = t_ms

    def uplink_rate(self, mobility_index):
        if   mobility_index <= 0.10: snr = SNR_DB_BY_MOBILITY["static"]
        elif mobility_index <= 0.30: snr = SNR_DB_BY_MOBILITY["low"]
        elif mobility_index <= 0.60: snr = SNR_DB_BY_MOBILITY["medium"]
        else:                        snr = SNR_DB_BY_MOBILITY["high"]
        return BANDWIDTH_HZ * math.log2(1.0 + 10**(snr/10.0))

    def evaluate(self, task, a):
        # returns (latency_ms, device_energy_J) WITHOUT mutating state
        cyc  = task["cpu_cycles"]; bits = task["data_size_bytes"]*8.0
        if a == 0:
            # local runs on the requesting device: no shared queue
            lat = cyc/self.cap[0]*1000.0
            return lat, cyc*KAPPA_DEVICE
        q_ms = self.backlog[a]/self.cap[a]*1000.0
        r_up = self.uplink_rate(task["mobility_index"])
        t_up = bits/r_up*1000.0
        t_bh = bits/self.backhaul[a]*1000.0
        t_cp = cyc/self.cap[a]*1000.0
        t_dn = (bits*RESULT_RATIO)/(2.0*r_up)*1000.0
        lat  = t_up + t_bh + self.prop[a] + q_ms + t_cp + t_dn
        e    = P_TX_W*(t_up/1000.0) + P_IDLE_W*max(0.0,(lat-t_up))/1000.0
        return lat, e

    def cost(self, task, a):
        t = TIER[a]
        return (PRICE_CYCLE[t]*task["cpu_cycles"] +
                PRICE_BIT[t]*task["data_size_bytes"]*8.0)

    def cost_ref(self, task):
        return (PRICE_CYCLE[CLOUD]*task["cpu_cycles"] +
                PRICE_BIT[CLOUD]*task["data_size_bytes"]*8.0)

    def evaluate_all(self, task):
        cyc = task["cpu_cycles"]; bits = task["data_size_bytes"]*8.0
        r_up = self.uplink_rate(task["mobility_index"])
        t_up = bits/r_up*1000.0
        lat = (t_up + bits/self.backhaul*1000.0 + self.prop
               + self.backlog/self.cap*1000.0 + cyc/self.cap*1000.0
               + (bits*RESULT_RATIO)/(2.0*r_up)*1000.0)
        e = P_TX_W*(t_up/1000.0) + P_IDLE_W*np.maximum(0.0, lat-t_up)/1000.0
        lat = lat.copy(); e = e.copy()
        lat[0] = cyc/self.cap[0]*1000.0; e[0] = cyc*KAPPA_DEVICE
        return lat, e

    def reward(self, lat, energy, deadline, e_local, cost, cost_ref):
        ok  = 1.0 if lat <= deadline else 0.0
        rl  = float(np.clip(1.0 - lat/max(deadline,1e-6), 0.0, 1.0))
        re  = float(np.clip(1.0 - energy/max(e_local,1e-9), 0.0, 1.0))
        rc  = float(np.clip(1.0 - cost/max(cost_ref,1e-12), 0.0, 1.0))
        return W_SUCCESS*ok + W_LAT*rl + W_ENERGY*re + W_COST*rc, ok

    def step(self, task, a):
        lat, e = self.evaluate(task, a)
        r, ok = self.reward(lat, e, task["deadline_ms"], task["cpu_cycles"]*KAPPA_DEVICE,
                            self.cost(task,a), self.cost_ref(task))
        if a != 0: self.backlog[a] += task["cpu_cycles"]
        self.nserved[a] += 1
        return r, lat, e, ok

    def node_features(self):
        # [cap_norm, backlog_ratio, queue_ms_norm, prop_norm, tier onehot(4)]
        q = self.backlog/self.cap*1000.0
        f = np.zeros((N_NODES, 8), dtype=np.float32)
        f[:,0] = self.cap/2.5e11
        f[:,1] = np.clip(self.backlog/(self.cap*0.5), 0, 3)
        f[:,2] = np.clip(q/100.0, 0, 3)
        f[:,3] = self.prop/70.0
        for i in range(N_NODES): f[i, 4+TIER[i]] = 1.0
        return f


TASK_FEAT_DIM = 8
def task_features(task, env):
    return np.array([
        math.log10(task["cpu_cycles"])/10.0,
        math.log10(task["data_size_bytes"])/8.0,
        task["deadline_ms"]/400.0,
        task["mobility_index"],
        task["priority"]/300.0,
        min(task["cpu_cycles"]/2e9, 2.0),                 # local compute time (s)
        min(task["data_size_bytes"]*8/env.uplink_rate(task["mobility_index"]), 2.0),
        min(task["deadline_ms"]/(task["cpu_cycles"]/2e9*1000.0+1e-6), 3.0)/3.0,  # local slack
    ], dtype=np.float32)


def make_stream(df, env, mean_interarrival_ms):
    rng = np.random.RandomState(1234)
    ia = rng.exponential(mean_interarrival_ms, len(df))
    arr = np.cumsum(ia)
    recs = []
    for i, row in enumerate(df.itertuples(index=False)):
        d = dict(cpu_cycles=float(row.cpu_cycles), data_size_bytes=float(row.data_size_bytes),
                 mobility_index=float(row.mobility_index), priority=float(row.priority),
                 deadline_ms=float(row.deadline_raw_ms)*env.deadline_scale,
                 arrival_ms=float(arr[i]), source=row.source, task_id=int(row.task_id))
        recs.append(d)
    return recs


# ---- policies used for calibration / baselines ----
_PC = np.array([PRICE_CYCLE[t] for t in TIER])
_PB = np.array([PRICE_BIT[t]   for t in TIER])

def reward_all(env, task):
    lat, e = env.evaluate_all(task); D = task["deadline_ms"]
    cyc = task["cpu_cycles"]; bits = task["data_size_bytes"]*8.0
    cost = _PC*cyc + _PB*bits
    cref = PRICE_CYCLE[CLOUD]*cyc + PRICE_BIT[CLOUD]*bits
    return (W_SUCCESS*(lat <= D)
            + W_LAT*np.clip(1.0 - lat/max(D,1e-6), 0, 1)
            + W_ENERGY*np.clip(1.0 - e/max(cyc*KAPPA_DEVICE,1e-9), 0, 1)
            + W_COST*np.clip(1.0 - cost/max(cref,1e-12), 0, 1)), lat, e

def myopic_oracle_action(env, task):
    return int(np.argmax(reward_all(env, task)[0]))

def greedy_latency_action(env, task):
    return int(np.argmin(env.evaluate_all(task)[0]))


def run_policy(env, stream, action_fn, collect=False):
    env.reset()
    R=[]; L=[]; E=[]; OK=[]; A=[]; DT=[]
    for task in stream:
        env.advance_to(task["arrival_ms"])
        t0=time.perf_counter(); a=action_fn(env, task); DT.append((time.perf_counter()-t0)*1000)
        r,lat,e,ok = env.step(task, a)
        R.append(r); L.append(lat); E.append(e); OK.append(ok); A.append(a)
    out = dict(reward=float(np.mean(R)), latency=float(np.mean(L)), energy=float(np.mean(E)),
               success=float(np.mean(OK)), miss=float(1-np.mean(OK)),
               decision_ms=float(np.mean(DT)),
               offload_rate=float(np.mean(np.array(A)>0)))
    if collect: out["_raw"]=dict(R=R,L=L,E=E,OK=OK,A=A)
    return out


def calibrate(df, sites, verbose=True):
    # 1) arrival rate -> target edge-tier utilisation
    probe = OffloadingEnv(seed=0, sites=sites)
    mean_cyc = float(df["cpu_cycles"].mean())
    edge_cap = probe.cap[1:1+NUM_EDGE].sum()
    ia = (mean_cyc/edge_cap)*1000.0/TARGET_EDGE_UTIL
    # 2) deadline scale -> target myopic-oracle miss rate
    sub = df.head(1200)
    lo, hi = 0.15, 6.0
    for _ in range(14):
        mid = (lo+hi)/2
        env = OffloadingEnv(seed=0, sites=sites, deadline_scale=mid)
        st  = make_stream(sub, env, ia)
        m   = run_policy(env, st, myopic_oracle_action)["miss"]
        if m > TARGET_ORACLE_MISS: lo = mid
        else: hi = mid
    scale = (lo+hi)/2
    if verbose:
        print("Calibration")
        print("  mean inter-arrival     : %.3f ms  (target edge util %.0f%%)" % (ia, TARGET_EDGE_UTIL*100))
        print("  deadline scale factor  : %.3f    (target oracle miss %.0f%%)" % (scale, TARGET_ORACLE_MISS*100))
    return ia, scale

In [6]:
ia_ms, dl_scale = calibrate(df, sites)
env      = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale)
eval_env = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale)
# Three-way split. Checkpoint selection and all hyper-parameter choices use VAL only;
# TEST is touched exactly once per configuration, at the end.
_a, _b = int(len(df)*0.60), int(len(df)*0.75)
train_stream = make_stream(df.iloc[:_a], env, ia_ms)
val_stream   = make_stream(df.iloc[_a:_b].reset_index(drop=True), env, ia_ms)
test_stream  = make_stream(df.iloc[_b:].reset_index(drop=True), env, ia_ms)
print("train %d | validation %d | test %d tasks"
      % (len(train_stream), len(val_stream), len(test_stream)))

Calibration
  mean inter-arrival     : 11.888 ms  (target edge util 90%)
  deadline scale factor  : 2.565    (target oracle miss 6%)
train 4800 | validation 1200 | test 2000 tasks

In [7]:
# ============================ GATE 1: PHYSICS SANITY ============================
probe = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale); probe.reset()
light = dict(cpu_cycles=8e6,  data_size_bytes=4e3, deadline_ms=40,  mobility_index=0.05, priority=100)
heavy = dict(cpu_cycles=2.0e9, data_size_bytes=2e5, deadline_ms=300, mobility_index=0.05, priority=100)
bigdata = dict(cpu_cycles=3e7, data_size_bytes=1.5e7, deadline_ms=400, mobility_index=0.80, priority=100)
E1, F1, C1 = 1, 1+NUM_EDGE, 1+NUM_EDGE+NUM_FOG

checks, PHYS = [], {}
for nm, t in [("light",light), ("heavy",heavy), ("big-data",bigdata)]:
    PHYS[nm] = {k: probe.evaluate(t, a)[0] for k, a in
                [("local",0), ("edge",E1), ("fog",F1), ("cloud",C1)]}

checks.append(("cloud RTT > edge RTT for a small task",
               PHYS["light"]["cloud"] > PHYS["light"]["edge"]))
checks.append(("cloud still beats local on a compute-heavy task",
               PHYS["heavy"]["cloud"] < PHYS["heavy"]["local"]))
checks.append(("local beats cloud on a small task (edge computing premise)",
               PHYS["light"]["local"] < PHYS["light"]["cloud"]))
e_off = probe.evaluate(bigdata, E1)[1]; e_loc = bigdata["cpu_cycles"]*KAPPA_DEVICE
checks.append(("radio energy dominates for a large-payload/light-compute task", e_off > e_loc))
_g = run_policy(eval_env, test_stream, greedy_latency_action)
checks.append(("deadline misses are non-trivial (5%-40%) under a strong heuristic",
               0.03 <= _g["miss"] <= 0.40))
_r = run_policy(eval_env, test_stream, lambda e,t: np.random.randint(N_NODES))
checks.append(("a sensible heuristic beats random", _g["reward"] > _r["reward"]))
before = probe.backlog[E1]
for _ in range(60): probe.step(heavy, E1)
checks.append(("loading a node degrades it (queueing is live)", probe.backlog[E1] > before))

print("GATE 1 - PHYSICS SANITY\n" + "-"*62)
for name, ok in checks: print("  [%s] %s" % ("PASS" if ok else "FAIL", name))
assert all(ok for _, ok in checks), "GATE 1 FAILED - fix the environment before continuing."
print("-"*62 + "\nGATE 1 PASSED\n")
print("latency (ms) by target:")
print(pd.DataFrame(PHYS).T.round(2))
RESULTS["gate1"] = {n: bool(o) for n, o in checks}; RESULTS["physics_table"] = PHYS

GATE 1 - PHYSICS SANITY
--------------------------------------------------------------
  [PASS] cloud RTT > edge RTT for a small task
  [PASS] cloud still beats local on a compute-heavy task
  [PASS] local beats cloud on a small task (edge computing premise)
  [PASS] radio energy dominates for a large-payload/light-compute task
  [PASS] deadline misses are non-trivial (5%-40%) under a strong heuristic
  [PASS] a sensible heuristic beats random
  [PASS] loading a node degrades it (queueing is live)
--------------------------------------------------------------
GATE 1 PASSED

latency (ms) by target:
           local    edge     fog   cloud
light        4.0    4.97   20.01   57.17
heavy     1000.0  191.13   63.05   70.85
big-data    15.0  616.81  642.27  775.06

## §3 — Oracle upper bound and **Gate 2**

The *myopic oracle* brute-forces all 19 actions at every step and takes the reward-maximising
one given the current network state. It is not a globally optimal policy (it cannot reason
about future congestion), but it bounds what any per-step-greedy method can achieve and is
the right reference for how much a learned policy can add.

**The gap between the best heuristic and the oracle is the available headroom.**

In [8]:
ref_policies = {
    "oracle":     myopic_oracle_action,
    "greedy":     greedy_latency_action,
    "random":     lambda e,t: np.random.randint(N_NODES),
    "local_only": lambda e,t: 0,
    "all_cloud":  lambda e,t: 1+NUM_EDGE+NUM_FOG,
}
np.random.seed(0)
REF = {k: run_policy(eval_env, test_stream, f) for k, f in ref_policies.items()}
tbl = pd.DataFrame(REF).T[["reward","latency","energy","miss","offload_rate","decision_ms"]]
tbl.columns = ["Reward","Latency (ms)","Device energy (J)","Deadline miss","Offload rate","Decision (ms)"]
display(tbl.round(4))

best_heur = max((v["reward"], k) for k, v in REF.items() if k != "oracle")
HEADROOM = (REF["oracle"]["reward"] - best_heur[0]) / best_heur[0] * 100
print("\nGATE 2 - HEADROOM\n" + "-"*62)
print("  best heuristic : %-10s reward %.4f" % (best_heur[1], best_heur[0]))
print("  myopic oracle  : %-10s reward %.4f" % ("oracle", REF["oracle"]["reward"]))
print("  HEADROOM       : %.2f%%   (gate requires >= 5%%)" % HEADROOM)
assert HEADROOM >= 5.0, ("GATE 2 FAILED - headroom %.2f%%. A heuristic is already near-optimal, "
                         "so no learning result here would be meaningful. Revisit §2." % HEADROOM)
print("-"*62 + "\nGATE 2 PASSED - there is a real learning problem.\n")
RESULTS["reference"] = {k: {m: v[m] for m in ["reward","latency","energy","miss","offload_rate","decision_ms"]}
                        for k, v in REF.items()}
RESULTS["headroom_pct"] = float(HEADROOM)

,Reward,Latency (ms),Device energy (J),Deadline miss,Offload rate,Decision (ms)
oracle,0.8812,115.1329,0.0517,0.060,0.9895,0.0231
greedy,0.8196,55.6673,0.0340,0.062,0.9305,0.0094
random,0.7283,204.9696,0.1259,0.194,0.9520,0.0013
local_only,0.6365,555.8301,1.1117,0.384,0.0000,0.0001
all_cloud,0.5102,100.4318,0.0446,0.133,1.0000,0.0001

GATE 2 - HEADROOM
--------------------------------------------------------------
  best heuristic : greedy     reward 0.8196
  myopic oracle  : oracle     reward 0.8812
  HEADROOM       : 7.52%   (gate requires >= 5%)
--------------------------------------------------------------
GATE 2 PASSED - there is a real learning problem.

## §4 — LSH engine · **Objective 1**

Proposal §8.2 specifies LSH for *similarity-based clustering to lower the complexity of
searching for optimal offloading targets*. So Objective 1 is evaluated on what LSH is
actually for: **retrieval quality and query-time scaling**, measured against exhaustive
nearest-neighbour search as ground truth.

Three defects in the original implementation are fixed here:
1. reuse was gated on `avg_reward > 0`, always true, so it memorised random exploration;
2. the LSH **verification** step was missing — buckets were used without checking similarity;
3. features were all-positive, so projection signs and cosine similarity both saturated
   (81 distinct buckets over the whole task space). Standardisation fixes this.

In [9]:
class LSHCache:
    # Proper LSH: hash -> CANDIDATES -> exact similarity verification -> reuse.
    # The original implementation skipped verification entirely and gated reuse on
    # "avg_reward > 0", which was always true, so it memorised random exploration.
    def __init__(self, dim=TASK_FEAT_DIM, tables=4, bits=12, seed=0,
                 sim_thresh=0.99, min_count=2, bucket_cap=40):
        rng = np.random.RandomState(seed)
        self.proj = [rng.randn(bits, dim) for _ in range(tables)]
        self.sim_thresh = sim_thresh; self.min_count = min_count
        self.bucket_cap = bucket_cap
        self.store = {}                      # key -> list of (zfeat, action, reward)
        self.mu = np.zeros(dim, dtype=np.float32); self.sd = np.ones(dim, dtype=np.float32)
        self.hits = 0; self.queries = 0
        self.r_ema = None; self.ema_a = 0.01
        self.eval_conf = 99.0   # inference uses the Q-network; LSH does pruning only

    def fit(self, feats):
        # Standardise: raw task features are all-positive, so random-projection signs
        # and cosine similarity both saturate. Centering makes the hash discriminative.
        F = np.asarray(feats, dtype=np.float32)
        self.mu = F.mean(0); self.sd = F.std(0) + 1e-6

    def _z(self, tf):
        return (tf - self.mu) / self.sd

    def _keys(self, z, lb):
        return [(t, lb, tuple((P @ z > 0).astype(np.int8))) for t, P in enumerate(self.proj)]

    @staticmethod
    def load_bucket(env):
        u = float(np.mean(env.backlog[1:] / env.cap[1:]))
        return int(np.clip(u * 4, 0, 3))

    def lookup(self, tf, env):
        self.queries += 1
        z = self._z(tf); nq = np.linalg.norm(z) + 1e-9
        agg = {}
        for k in self._keys(z, self.load_bucket(env)):
            for feat, a, r in self.store.get(k, []):
                sim = float(np.dot(feat, z) / ((np.linalg.norm(feat) + 1e-9) * nq))
                if sim >= self.sim_thresh:                      # VERIFICATION step
                    s, n = agg.get(a, (0.0, 0)); agg[a] = (s + r, n + 1)
        if not agg: return None, 0.0
        a_best, (s, n) = max(agg.items(), key=lambda kv: kv[1][0] / kv[1][1])
        if n < self.min_count: return None, 0.0
        if self.r_ema is not None and s / n < self.r_ema: return None, 0.0
        self.hits += 1
        return int(a_best), float(min(n / 8.0, 1.0))

    def update(self, tf, env, action, reward, allow_write):
        self.r_ema = reward if self.r_ema is None else (1-self.ema_a)*self.r_ema + self.ema_a*reward
        if not allow_write: return
        if self.r_ema is not None and reward < self.r_ema: return
        z = self._z(tf)
        for k in self._keys(z, self.load_bucket(env)):
            b = self.store.setdefault(k, [])
            b.append((z, action, reward))
            if len(b) > self.bucket_cap: b.pop(0)

    def stats(self):
        return dict(hit_rate=self.hits / max(self.queries, 1),
                    buckets=len(self.store),
                    entries=sum(len(v) for v in self.store.values()),
                    queries=self.queries)

In [10]:
# ---- Objective 1 experiment: LSH retrieval vs exhaustive search ----
feat_bank = np.array([task_features(t, env) for t in train_stream], dtype=np.float32)
lsh_probe = LSHCache(seed=0); lsh_probe.fit(feat_bank)
Z = (feat_bank - lsh_probe.mu) / lsh_probe.sd
Zn = Z / (np.linalg.norm(Z, axis=1, keepdims=True) + 1e-9)

def exhaustive_topk(qi, k=10, upto=None):
    S = Zn[:upto] @ Zn[qi]; S[qi] = -2
    return set(np.argpartition(-S, k)[:k])

def lsh_candidates(qi, upto, index):
    z = Z[qi]; out = set()
    for key in lsh_probe._keys(z, 0): out |= index.get(key, set())
    out.discard(qi); return out

# LSH's advantage is asymptotic. Extend the index with jittered replicas so the
# O(N) vs O(1) crossover is actually reached. This is an index-scaling study;
# it does not claim 140k real traces.
_base = Z.copy()
Z = np.vstack([_base] + [_base + np.random.RandomState(s).normal(0, 0.8, _base.shape)
                         for s in range(35)]).astype(np.float32)
Zn = Z / (np.linalg.norm(Z, axis=1, keepdims=True) + 1e-9)
sizes = [s for s in [1000, 5000, 20000, 60000, 140000] if s <= len(Z)]
lsh_rows = []
for N in sizes:
    # Hash width scales with log N so bucket occupancy stays bounded; with a fixed
    # width, candidate lists grow linearly with N and the O(1) property is lost.
    # More hash bits sharpen selectivity but cost recall; more tables restore it.
    lsh_probe = LSHCache(seed=0, tables=10, bits=max(10, int(np.log2(N)) - 1))
    lsh_probe.fit(feat_bank)
    index = {}
    for i in range(N):
        for key in lsh_probe._keys(Z[i], 0): index.setdefault(key, set()).add(i)
    qs = np.random.RandomState(0).choice(N, min(120, N), replace=False)
    rec, t_l, t_e, cand = [], [], [], []
    for qi in qs:
        t0 = time.perf_counter()
        for _ in range(5): c = lsh_candidates(qi, N, index)
        t_l.append((time.perf_counter()-t0)/5)
        t0 = time.perf_counter()
        for _ in range(5): true = exhaustive_topk(qi, 10, N)
        t_e.append((time.perf_counter()-t0)/5)
        rec.append(len(c & true)/10.0); cand.append(len(c))
    lsh_rows.append(dict(N=N, recall_at_10=float(np.mean(rec)),
                         lsh_ms=float(np.mean(t_l)*1000), exhaustive_ms=float(np.mean(t_e)*1000),
                         speedup=float(np.mean(t_e)/max(np.mean(t_l),1e-9)),
                         candidates=float(np.mean(cand)),
                         search_space_reduction=100*(1-np.mean(cand)/N)))
LSH_SCALE = pd.DataFrame(lsh_rows)
display(LSH_SCALE.round(3))
print("\nOBJECTIVE 1 RESULT")
print("  recall@10 vs exhaustive search : %.1f%%" % (100*LSH_SCALE.recall_at_10.mean()))
print("  query speedup at N=%d          : %.1fx" % (LSH_SCALE.N.iloc[-1], LSH_SCALE.speedup.iloc[-1]))
print("  search-space reduction at N=%d : %.1f%%" % (LSH_SCALE.N.iloc[-1],
                                                     LSH_SCALE.search_space_reduction.iloc[-1]))
RESULTS["objective1_lsh"] = LSH_SCALE.to_dict("records")

,N,recall_at_10,lsh_ms,exhaustive_ms,speedup,candidates,search_space_reduction
0,1000,0.982,0.031,0.009,0.292,130.667,86.933
1,5000,0.998,0.047,0.014,0.295,586.475,88.270
2,20000,0.907,0.047,0.053,1.128,768.483,96.158
3,60000,0.918,0.090,0.149,1.667,1475.933,97.540
4,140000,0.932,0.134,0.330,2.473,2342.783,98.327

OBJECTIVE 1 RESULT
  recall@10 vs exhaustive search : 94.8%
  query speedup at N=140000          : 2.5x
  search-space reduction at N=140000 : 98.3%

## §5 — Graph-RL agent · **Objective 2**

Four defects fixed relative to the original code:

| Original | Consequence | Fix here |
|---|---|---|
| GAT had no backward pass | "graph learning" was a fixed random projection | GAT trained end-to-end with the Q-head |
| Graph embedding mean-pooled over all nodes | state could not distinguish nodes, so node selection was unlearnable | **per-node scoring**: each candidate scored separately |
| `next_state` recomputed from the *same* task, `done` always False | degenerate self-bootstrapping target | `next_state` is the **next** task; `done` at episode end |
| Training-phase averages reported as results | reported performance included random exploration | frozen weights, **ε = 0**, held-out tasks |

In the integrated system LSH guides **exploration** (smaller effective search space during
training); the final policy is always produced by the Q-network, so inference carries no
cache-accuracy risk.

In [11]:
import math, time, random, copy
import numpy as np, torch
import torch.nn as nn, torch.nn.functional as F
from collections import deque

DEV = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NODE_FEAT_DIM = 8
EMB_DIM, HEADS, HIDDEN = 32, 4, 128


# ---------------- trainable GAT (the original code's GAT had NO backward pass) ----------
class GATLayer(nn.Module):
    def __init__(self, fin, fout, heads):
        super().__init__()
        assert fout % heads == 0
        self.h, self.d = heads, fout // heads
        self.W = nn.Linear(fin, fout, bias=False)
        self.a_src = nn.Parameter(torch.empty(heads, self.d)); nn.init.xavier_uniform_(self.a_src)
        self.a_dst = nn.Parameter(torch.empty(heads, self.d)); nn.init.xavier_uniform_(self.a_dst)

    def forward(self, x, adj):
        B, N, _ = x.shape
        h = self.W(x).view(B, N, self.h, self.d)
        es = (h * self.a_src).sum(-1)                       # (B,N,H)
        ed = (h * self.a_dst).sum(-1)
        e = F.leaky_relu(es.unsqueeze(2) + ed.unsqueeze(1), 0.2)   # (B,N,N,H)
        mask = adj.view(1, N, N, 1) > 0
        e = e.masked_fill(~mask, float("-inf"))
        alpha = torch.softmax(e, dim=2)
        out = torch.einsum("bijh,bjhd->bihd", alpha, h)
        return out.reshape(B, N, self.h * self.d)


class GraphEncoder(nn.Module):
    def __init__(self, fin=NODE_FEAT_DIM, emb=EMB_DIM, heads=HEADS):
        super().__init__()
        self.g1 = GATLayer(fin, emb, heads)
        self.g2 = GATLayer(emb, emb, heads)

    def forward(self, node_raw, adj):
        h = F.elu(self.g1(node_raw, adj))
        return F.elu(self.g2(h, adj))


class QNet(nn.Module):
    # Scores EACH candidate node separately (the original mean-pooled the graph,
    # destroying the per-node information needed to choose a node).
    def __init__(self, use_graph=True):
        super().__init__()
        self.use_graph = use_graph
        self.enc = GraphEncoder() if use_graph else None
        din = TASK_FEAT_DIM + NODE_FEAT_DIM + (EMB_DIM if use_graph else 0)
        self.mlp = nn.Sequential(nn.Linear(din, HIDDEN), nn.ReLU(),
                                 nn.Linear(HIDDEN, HIDDEN), nn.ReLU(),
                                 nn.Linear(HIDDEN, 1))

    def forward(self, task, node_raw, adj):
        B, N, _ = node_raw.shape
        parts = [task.unsqueeze(1).expand(B, N, TASK_FEAT_DIM), node_raw]
        if self.use_graph:
            parts.append(self.enc(node_raw, adj))
        return self.mlp(torch.cat(parts, -1)).squeeze(-1)          # (B,N)


class FlatQNet(nn.Module):
    # Literature baseline "Standard DQN": task features only -> 19 Q-values, no node state.
    def __init__(self):
        super().__init__()
        self.mlp = nn.Sequential(nn.Linear(TASK_FEAT_DIM, HIDDEN), nn.ReLU(),
                                 nn.Linear(HIDDEN, HIDDEN), nn.ReLU(),
                                 nn.Linear(HIDDEN, N_NODES))

    def forward(self, task, node_raw, adj):
        return self.mlp(task)


# ---------------- LSH policy cache (Objective 1) ----------------
class Replay:
    def __init__(self, cap=20000):
        self.b = deque(maxlen=cap)
    def push(self, *x): self.b.append(x)
    def __len__(self): return len(self.b)
    def sample(self, n):
        batch = random.sample(self.b, min(n, len(self.b)))
        t, nr, a, r, t2, nr2, d = zip(*batch)
        T = lambda z, dt=torch.float32: torch.tensor(np.array(z), dtype=dt, device=DEV)
        return (T(t), T(nr), torch.tensor(a, dtype=torch.long, device=DEV),
                T(r), T(t2), T(nr2), T(d))


class Agent:
    def __init__(self, adj, use_graph=True, use_lsh=True, flat=False, seed=0, lr=3e-4,
                 use_hpfoo=False, topk=6, hpfoo_schedule=None):
        torch.manual_seed(seed)
        self.flat = flat
        self.q  = (FlatQNet() if flat else QNet(use_graph)).to(DEV)
        self.qt = (FlatQNet() if flat else QNet(use_graph)).to(DEV)
        self.qt.load_state_dict(self.q.state_dict())
        self.opt = torch.optim.Adam(self.q.parameters(), lr=lr)
        self.adj = torch.tensor(adj, dtype=torch.float32, device=DEV)
        self.lsh = LSHCache(seed=seed) if use_lsh else None
        self.hpfoo = (HPFOO(seed=seed, schedule=hpfoo_schedule)
                      if use_hpfoo else None)
        self.topk = topk; self.n_cand = []
        self.mem = Replay(); self.eps = 1.0; self.steps = 0
        self.gamma = 0.95; self.tau_update = 200; self.learn_every = 2; self.batch = 128

    def q_values(self, tf, node_raw):
        with torch.no_grad():
            t = torch.tensor(tf, dtype=torch.float32, device=DEV).unsqueeze(0)
            n = torch.tensor(node_raw, dtype=torch.float32, device=DEV).unsqueeze(0)
            return self.q(t, n, self.adj)[0].cpu().numpy()

    def candidates(self, tf, env, q):
        # LSH prunes the search space the optimiser must evaluate (proposal 8.2).
        cand = np.argsort(-q)[:self.topk]
        if self.lsh is not None:
            a, conf = self.lsh.lookup(tf, env)
            if a is not None and a not in cand: cand = np.append(cand, a)
        self.n_cand.append(len(cand))
        return cand

    def act(self, tf, node_raw, env, task=None, greedy=False):
        if not greedy and np.random.random() < self.eps:
            if self.lsh is not None:
                a, conf = self.lsh.lookup(tf, env)
                if a is not None and np.random.random() < 0.7:
                    return int(a), True
            return int(np.random.randint(N_NODES)), False
        q = self.q_values(tf, node_raw)
        if self.hpfoo is None or not self.hpfoo.fitted or task is None:
            return int(np.argmax(q)), False
        cand = self.candidates(tf, env, q)
        F = self.hpfoo.features(env, task, cand)
        U = self.hpfoo.utility(F); Q = q[cand]
        nz = lambda v: (v - v.min())/(np.ptp(v) + 1e-9)
        al = self.hpfoo.alpha()
        return int(cand[int(np.argmax(al*nz(Q) + (1-al)*nz(U)))]), False

    def learn(self, batch=64):
        if len(self.mem) < 500: return None
        t, nr, a, r, t2, nr2, d = self.mem.sample(batch)
        q = self.q(t, nr, self.adj).gather(1, a.unsqueeze(1)).squeeze(1)
        with torch.no_grad():
            a2 = self.q(t2, nr2, self.adj).argmax(1, keepdim=True)      # Double DQN
            q2 = self.qt(t2, nr2, self.adj).gather(1, a2).squeeze(1)
            y = r + self.gamma * q2 * (1 - d)
        loss = F.smooth_l1_loss(q, y)
        self.opt.zero_grad(); loss.backward()
        nn.utils.clip_grad_norm_(self.q.parameters(), 5.0); self.opt.step()
        self.steps += 1
        if self.steps % self.tau_update == 0: self.qt.load_state_dict(self.q.state_dict())
        return float(loss)


def evaluate(agent, env, stream):
    # Held-out evaluation: frozen weights, epsilon = 0. The original code reported
    # training-phase averages (including random exploration) as final performance.
    env.reset(); R=[];L=[];E=[];OK=[];A=[];DT=[]
    for task in stream:
        env.advance_to(task["arrival_ms"])
        tf = task_features(task, env); nr = env.node_features()
        t0 = time.perf_counter(); a,_ = agent.act(tf, nr, env, task=task, greedy=True)
        DT.append((time.perf_counter()-t0)*1000)
        r,lat,e,ok = env.step(task, a)
        R.append(r);L.append(lat);E.append(e);OK.append(ok);A.append(a)
    return dict(reward=float(np.mean(R)), latency=float(np.mean(L)), energy=float(np.mean(E)),
                success=float(np.mean(OK)), miss=float(1-np.mean(OK)),
                decision_ms=float(np.mean(DT)), offload_rate=float(np.mean(np.array(A)>0)),
                actions=A)


def train(agent, env, train_stream, val_env, val_stream, episodes, ep_len,
          eval_every=5, verbose=True, tag="", early_stop=True):
    # Model selection uses the VALIDATION stream only. The test stream is never
    # touched during training, so checkpoint selection cannot leak into the result.
    curve = []
    best_r, best_q, best_gb = -1e9, None, None
    total = episodes * ep_len
    step_i = 0
    for ep in range(episodes):
        s = (ep * ep_len) % max(1, len(train_stream) - ep_len)
        chunk = train_stream[s:s+ep_len]
        env.reset()
        prev = None
        for i, task in enumerate(chunk):
            env.advance_to(task["arrival_ms"])
            tf = task_features(task, env); nr = env.node_features()
            a, from_cache = agent.act(tf, nr, env, task=task)
            r, lat, e, ok = env.step(task, a)
            nr2 = env.node_features()
            nxt = chunk[i+1] if i+1 < len(chunk) else task
            tf2 = task_features(nxt, env)
            done = 1.0 if i == len(chunk)-1 else 0.0
            agent.mem.push(tf, nr, a, r, tf2, nr2, done)     # next state = NEXT task
            if agent.lsh is not None:
                agent.lsh.update(tf, env, a, r, allow_write=(agent.eps < 0.85))
            if agent.hpfoo is not None:
                agent.hpfoo.observe(agent.hpfoo.features(env, task, np.array([a]))[0], r)
                if step_i % 250 == 0: agent.hpfoo.optimise()
            if step_i % agent.learn_every == 0: agent.learn(agent.batch)
            step_i += 1
            agent.eps = max(0.05, 1.0 - step_i / (0.6 * total))
        if (ep+1) % eval_every == 0 or ep == episodes-1:
            m = evaluate(agent, val_env, val_stream)
            curve.append((ep+1, m["reward"], m["miss"]))
            if m["reward"] > best_r:
                best_r = m["reward"]
                best_q = copy.deepcopy(agent.q.state_dict())
                best_gb = None if agent.hpfoo is None else agent.hpfoo.gb.copy()
            if verbose:
                print("    [%s] ep %3d/%d  val reward %.4f  miss %5.2f%%  eps %.2f"
                      % (tag, ep+1, episodes, m["reward"], m["miss"]*100, agent.eps))
    if early_stop and best_q is not None:
        agent.q.load_state_dict(best_q)
        if best_gb is not None: agent.hpfoo.gb = best_gb
        if verbose: print("    [%s] restored best checkpoint (val reward %.4f)" % (tag, best_r))
    agent.best_val = best_r
    return curve


# ================= HPFOO: Hybrid Particle-swarm / Firefly Offloading Optimiser =========
# Proposal Objective 3. Learns a linear multi-objective utility over OBSERVABLE node
# features from REALISED rewards (no simulator/oracle access), and fuses it with the
# GRL Q-values. LSH prunes the candidate set the optimiser searches (proposal 8.2).
HPFOO_DIM = 7          # 6 feature weights + 1 fusion coefficient alpha

class HPFOO:
    # Hybrid Pufferfish-Osprey Optimisation (HPFOO).
    #   Phase 1 - Osprey exploration      : position identification & hunting (OOA)
    #   Phase 2 - Pufferfish exploitation : defensive-inflation local search (POA)
    # Both phases use greedy selection: a candidate replaces the incumbent only if
    # its fitness improves, so the population fitness is monotonically non-decreasing.
    # Fitness ranks the six utility weights against realised rewards; it cannot score
    # the fusion coefficient alpha (index 6), which is selected on validation instead.
    def __init__(self, n_particles=14, seed=0, iters=6, lb=-3.0, ub=3.0,
                 schedule=None):
        schedule = PUFFERFISH_SCHEDULE if schedule is None else schedule
        rng = np.random.RandomState(seed); self.rng = rng
        self.lb, self.ub = float(lb), float(ub)
        self.X = rng.uniform(lb, ub, (n_particles, HPFOO_DIM))
        self.F = np.full(n_particles, -1e9)
        self.gb = self.X[0].copy(); self.gbf = -1e9
        self.iters = iters; self.t = 1
        self.buf_F, self.buf_r = [], []
        self._alpha_override = None
        self.fitted = False
        # ---- Requirement 2: step-size schedule state ----
        self.schedule = schedule
        self.n_calls = 0           # how many times optimise() has been invoked
        self.radius_log = []       # every radius actually applied, for reporting

    def step_radius(self, tau):
        """Pufferfish defensive-inflation radius for local iteration `tau`.

        legacy   : (ub-lb)/t,  t monotonic over the entire training run.
        reset    : (ub-lb)/tau, tau = 1..iters, fresh contraction each invocation.
        annealed : (ub-lb)/tau * 1/sqrt(1+k), k = invocation index. Coarse-to-fine
                   within an invocation, plus a global anneal across the run so the
                   population is not re-scattered late in training.
        """
        span = self.ub - self.lb
        if self.schedule == "legacy":
            rad = span / self.t
        elif self.schedule == "reset":
            rad = span / tau
        else:
            rad = span / tau / math.sqrt(1.0 + self.n_calls)
        self.radius_log.append(float(rad))
        return rad

    @staticmethod
    def features(env, task, cand):
        cap = env.cap[cand]
        q    = env.backlog[cand]/cap*1000.0
        comp = task["cpu_cycles"]/cap*1000.0
        prop = env.prop[cand]
        price = _PC[cand]*task["cpu_cycles"] + _PB[cand]*task["data_size_bytes"]*8.0
        D = max(task["deadline_ms"], 1e-6)
        est = q + comp + prop
        return np.stack([np.clip(q/100,0,5), np.clip(comp/100,0,5), prop/70.0,
                         price/(price.max()+1e-12), np.clip(est/D,0,3)/3.0,
                         (TIER[cand] == LOCAL).astype(float)], axis=1)

    def utility(self, F, w=None):
        w = self.gb if w is None else w
        return F @ w[:6]

    def alpha(self):
        if self._alpha_override is not None: return float(self._alpha_override)
        return float(1.0/(1.0+np.exp(-self.gb[6])))

    def set_alpha(self, a):
        self._alpha_override = None if a is None else float(np.clip(a, 0.0, 1.0))

    def observe(self, f_row, r):
        self.buf_F.append(f_row); self.buf_r.append(r)
        if len(self.buf_F) > 2000: self.buf_F.pop(0); self.buf_r.pop(0)

    def _fitness(self, W):
        # rank agreement between predicted utility and realised reward
        F = np.asarray(self.buf_F); r = np.asarray(self.buf_r)
        U = F @ W[:, :6].T
        Uc = U - U.mean(0); rc = r - r.mean()
        d = (np.linalg.norm(Uc, axis=0)*np.linalg.norm(rc) + 1e-9)
        return (Uc*rc[:, None]).sum(0)/d

    def optimise(self):
        if len(self.buf_F) < 200: return
        n = len(self.X)
        F = self._fitness(self.X)
        for _tau in range(1, self.iters + 1):
            self.t += 1

            # ---- Phase 1: Osprey exploration ----
            # x_new = x + r * (SF - I*x),  SF drawn from members with better fitness,
            # r ~ U(0,1),  I in {1,2}
            Xn = self.X.copy()
            for i in range(n):
                better = np.where(F > F[i])[0]
                SF = self.gb if len(better) == 0 else self.X[self.rng.choice(better)]
                r = self.rng.random(HPFOO_DIM)
                I = self.rng.randint(1, 3, HPFOO_DIM)
                Xn[i] = self.X[i] + r*(SF - I*self.X[i])
            Xn = np.clip(Xn, self.lb, self.ub)
            Fn = self._fitness(Xn)
            imp = Fn > F
            self.X[imp] = Xn[imp]; F[imp] = Fn[imp]

            # ---- Phase 2: Pufferfish exploitation ----
            # x_new = x + (1 - 2r) * R(tau, k)   : R is the scheduled radius, see
            # HPFOO.step_radius. The neighbourhood contracts as tau grows within an
            # invocation and as k grows across the training run.
            r = self.rng.random((n, HPFOO_DIM))
            Xn = np.clip(self.X + (1.0 - 2.0*r)*self.step_radius(_tau),
                         self.lb, self.ub)
            Fn = self._fitness(Xn)
            imp = Fn > F
            self.X[imp] = Xn[imp]; F[imp] = Fn[imp]

            j = int(np.argmax(F))
            if F[j] > self.gbf:
                self.gbf = float(F[j]); self.gb = self.X[j].copy()
        self.n_calls += 1
        self.F = F
        self.fitted = True

## §6–§7 — Training and held-out evaluation · **Objective 4**

Three learned variants (proposed, and two ablations) plus the reference policies from §3.

In [12]:
SPEC = {"lsh_grl_hpfoo": dict(use_graph=True,  use_lsh=True,  use_hpfoo=True),
        "lsh_grl":       dict(use_graph=True,  use_lsh=True,  use_hpfoo=False),
        "grl":           dict(use_graph=True,  use_lsh=False, use_hpfoo=False),
        "no_graph":      dict(use_graph=False, use_lsh=False, use_hpfoo=False),
        "dqn":           dict(flat=True,       use_lsh=False, use_hpfoo=False)}

def build_agent(kind, seed, topk=6, hpfoo_schedule=None):
    ag = Agent(env.adj, seed=seed, topk=topk, hpfoo_schedule=hpfoo_schedule,
               **SPEC[kind])
    if ag.lsh is not None: ag.lsh.fit(feat_bank)
    return ag

ALPHA_GRID = [0.0, 0.25, 0.5, 0.75, 1.0]

def train_one(kind, seed, verbose=True, topk=6, tune_alpha=True,
              hpfoo_schedule=None):
    set_seed(seed)
    e  = OffloadingEnv(seed=seed, sites=sites, deadline_scale=dl_scale)
    ve = OffloadingEnv(seed=seed, sites=sites, deadline_scale=dl_scale)
    te = OffloadingEnv(seed=seed, sites=sites, deadline_scale=dl_scale)
    ag = build_agent(kind, seed, topk, hpfoo_schedule)
    curve = train(ag, e, train_stream, ve, val_stream, P["EPISODES"], P["EP_LEN"],
                  eval_every=P["EVAL_EVERY"], verbose=verbose, tag=kind)
    # Fusion weight alpha is selected on VALIDATION. The metaheuristic cannot score it
    # (its fitness only ranks the six utility weights), so it is chosen here instead.
    # alpha = 1.0 (pure Q-network) is in the grid, so this can never select a policy
    # worse than the no-HPFOO ablation on validation.
    if tune_alpha and ag.hpfoo is not None and ag.hpfoo.fitted:
        best = (-1e9, None)
        for al in ALPHA_GRID:
            ag.hpfoo.set_alpha(al)
            r = evaluate(ag, ve, val_stream)["reward"]
            if r > best[0]: best = (r, al)
        ag.hpfoo.set_alpha(best[1]); ag.alpha_selected = best[1]
    m = evaluate(ag, te, test_stream)
    m["candidates"] = float(np.mean(ag.n_cand)) if ag.n_cand else float(N_NODES)
    m["alpha"] = getattr(ag, "alpha_selected", None)
    return ag, curve, m

### §7a — Sensitivity analyses (run BEFORE the main comparison)

`topk` (how many candidates HPFOO evaluates) and `alpha` (Q-network / HPFOO-utility fusion)
are both selected on the **validation** stream. Test figures are shown for transparency and
play no part in selection. Because `alpha = 1.0` (pure Q-network) and `topk = 19` (no pruning)
are both in the grids, this can never select a configuration worse than the ablated variants
on validation.

The HPFOO fitness ranks only the six utility weights, so it cannot score `alpha`; selecting
it here is the correct treatment.

In [13]:
# ---- topk sweep: selection on VALIDATION ----
TOPK_GRID = [3, 6, 10, N_NODES]
tk_rows = []
for tk in TOPK_GRID:
    _ag, _, m = train_one('lsh_grl_hpfoo', 0, verbose=False, topk=tk)
    _ve = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale)
    v = evaluate(_ag, _ve, val_stream)['reward']
    tk_rows.append(dict(topk=tk, val_reward=v, reward=m['reward'], latency=m['latency'],
                        miss_pct=m['miss']*100, candidates=m['candidates'],
                        reduction_pct=100*(1-m['candidates']/N_NODES),
                        decision_ms=m['decision_ms'], alpha=m['alpha']))
    print('  topk=%-3d val %.4f  test %.4f  miss %5.2f%%  cand %.1f'
          % (tk, v, m['reward'], m['miss']*100, m['candidates']))
TOPK = pd.DataFrame(tk_rows); display(TOPK.round(4))
TOPK_BEST = int(TOPK.loc[TOPK.val_reward.idxmax(), 'topk'])
print('\ntopk selected on validation : %d  (test reward at that setting: %.4f)'
      % (TOPK_BEST, float(TOPK.loc[TOPK.val_reward.idxmax(), 'reward'])))
RESULTS['sensitivity_topk'] = TOPK.to_dict('records'); RESULTS['topk_selected'] = TOPK_BEST

  topk=3   val 0.8732  test 0.8755  miss  7.45%  cand 3.5
  topk=6   val 0.8716  test 0.8738  miss  7.15%  cand 6.3
  topk=10  val 0.8716  test 0.8731  miss  7.80%  cand 10.2
  topk=19  val 0.8686  test 0.8728  miss  7.70%  cand 19.0

,topk,val_reward,reward,latency,miss_pct,candidates,reduction_pct,decision_ms,alpha
0,3,0.8732,0.8755,119.2378,7.45,3.4709,81.7322,0.7348,0.00
1,6,0.8716,0.8738,114.8303,7.15,6.3290,66.6895,0.7245,0.25
2,10,0.8716,0.8731,110.4256,7.80,10.1905,46.3657,0.7298,0.50
3,19,0.8686,0.8728,116.0814,7.70,19.0000,0.0000,0.7429,0.50

topk selected on validation : 3  (test reward at that setting: 0.8755)

In [14]:
# ---- alpha sweep at the selected topk (no retraining per alpha) ----
set_seed(0)
_ag, _, _ = train_one('lsh_grl_hpfoo', 0, verbose=False, topk=TOPK_BEST, tune_alpha=False)
_ve = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale)
_te = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale)
al_rows = []
for al in ALPHA_GRID:
    _ag.hpfoo.set_alpha(al)
    v = evaluate(_ag, _ve, val_stream); t = evaluate(_ag, _te, test_stream)
    al_rows.append(dict(alpha=al, val_reward=v['reward'], test_reward=t['reward'],
                        test_latency=t['latency'], test_miss_pct=t['miss']*100))
ALPHA = pd.DataFrame(al_rows)
_best_al = float(ALPHA.loc[ALPHA.val_reward.idxmax(), 'alpha'])
display(ALPHA.round(4))
print('\nalpha selected on validation : %.2f   (metaheuristic drift value: %.2f)'
      % (_best_al, 1/(1+np.exp(-_ag.hpfoo.gb[6]))))
RESULTS['sensitivity_alpha'] = ALPHA.to_dict('records')
RESULTS['alpha_selected'] = _best_al

   alpha  val_reward  test_reward  test_latency  test_miss_pct
0   0.00      0.8732       0.8755      119.2378           7.45
1   0.25      0.8729       0.8754      122.4361           7.45
2   0.50      0.8696       0.8733      121.7426           7.95
3   0.75      0.8600       0.8651      120.7663           8.95
4   1.00      0.8591       0.8606      118.5630           9.70

alpha selected on validation : 0.00   (metaheuristic drift value: 0.49)

### §7b — Main comparison at the validation-selected settings

Trained with `topk = TOPK_BEST`; `alpha` is re-selected on validation inside `train_one`.

In [15]:
LEARNED = {}; CURVES = {}
for kind in ["lsh_grl_hpfoo", "lsh_grl", "grl", "dqn"]:
    t0 = time.time(); print("training %s ..." % LABELS.get(kind, kind))
    ag, cur, m = train_one(kind, 0, topk=TOPK_BEST)
    LEARNED[kind] = m; CURVES[kind] = cur
    if ag.lsh is not None: RESULTS["lsh_"+kind] = ag.lsh.stats()
    if ag.n_cand: RESULTS["cand_"+kind] = dict(mean_candidates=float(np.mean(ag.n_cand)),
        reduction_pct=100*(1-float(np.mean(ag.n_cand))/N_NODES))
    print("  -> held-out reward %.4f | miss %.2f%% | %.0fs\n" % (m["reward"], m["miss"]*100, time.time()-t0))

training LSH-GRL-HPFOO (Proposed) ...
    [lsh_grl_hpfoo] ep   5/25  val reward 0.8673  miss  9.50%  eps 0.67
    [lsh_grl_hpfoo] ep  10/25  val reward 0.8712  miss  7.50%  eps 0.33
    [lsh_grl_hpfoo] ep  15/25  val reward 0.8707  miss  8.00%  eps 0.05
    [lsh_grl_hpfoo] ep  20/25  val reward 0.8713  miss  8.08%  eps 0.05
    [lsh_grl_hpfoo] ep  25/25  val reward 0.8712  miss  7.92%  eps 0.05
    [lsh_grl_hpfoo] restored best checkpoint (val reward 0.8713)
  -> held-out reward 0.8755 | miss 7.45% | 22s

training LSH-GRL (no HPFOO) ...
    [lsh_grl] ep   5/25  val reward 0.8691  miss  9.00%  eps 0.67
    [lsh_grl] ep  10/25  val reward 0.8561  miss 10.75%  eps 0.33
    [lsh_grl] ep  15/25  val reward 0.8652  miss  9.75%  eps 0.05
    [lsh_grl] ep  20/25  val reward 0.8649  miss  9.50%  eps 0.05
    [lsh_grl] ep  25/25  val reward 0.8639  miss  8.42%  eps 0.05
    [lsh_grl] restored best checkpoint (val reward 0.8691)
  -> held-out reward 0.8699 | miss 9.05% | 13s

training GRL only ...
    [grl] ep   5/25  val reward 0.8707  miss  7.92%  eps 0.67
    [grl] ep  10/25  val reward 0.8653  miss  8.17%  eps 0.33
    [grl] ep  15/25  val reward 0.8623  miss  9.25%  eps 0.05
    [grl] ep  20/25  val reward 0.8636  miss  9.17%  eps 0.05
    [grl] ep  25/25  val reward 0.8526  miss  8.50%  eps 0.05
    [grl] restored best checkpoint (val reward 0.8707)
  -> held-out reward 0.8727 | miss 7.85% | 12s

training Standard DQN ...
    [dqn] ep   5/25  val reward 0.6604  miss 38.67%  eps 0.67
    [dqn] ep  10/25  val reward 0.4749  miss 70.75%  eps 0.33
    [dqn] ep  15/25  val reward 0.5003  miss 69.00%  eps 0.05
    [dqn] ep  20/25  val reward 0.8004  miss 16.33%  eps 0.05
    [dqn] ep  25/25  val reward 0.7273  miss 24.92%  eps 0.05
    [dqn] restored best checkpoint (val reward 0.8004)
  -> held-out reward 0.7942 | miss 17.65% | 4s

In [16]:
ALL = {}
for k in ["lsh_grl_hpfoo","lsh_grl","grl","dqn"]: ALL[k] = {m: LEARNED[k][m] for m in
    ["reward","latency","energy","success","miss","offload_rate","decision_ms"]}
for k in ["greedy","random","local_only","all_cloud","oracle"]: ALL[k] = RESULTS["reference"][k]

MAIN = pd.DataFrame(ALL).T.loc[["lsh_grl_hpfoo","lsh_grl","grl","dqn","greedy","random","local_only","all_cloud","oracle"]]
MAIN.index = [LABELS[i] for i in MAIN.index]
MAIN = MAIN[["reward","latency","energy","miss","offload_rate","decision_ms"]]
MAIN.columns = ["Reward","Latency (ms)","Energy (J)","Deadline miss","Offload rate","Decision (ms)"]
display(MAIN.round(4))

prop, orc = ALL["lsh_grl_hpfoo"]["reward"], ALL["oracle"]["reward"]
print("\nHELD-OUT RESULT (frozen weights, epsilon = 0, unseen tasks)\n" + "="*66)
for k in ["lsh_grl","grl","dqn","greedy","random","local_only","all_cloud"]:
    print("  Proposed vs %-24s : %+7.2f%%" % (LABELS[k], (prop-ALL[k]["reward"])/ALL[k]["reward"]*100))
gap_closed = (prop-ALL["greedy"]["reward"])/(orc-ALL["greedy"]["reward"])*100
print("  oracle headroom closed         : %6.1f%%" % gap_closed)
print("="*66)
RESULTS["main_comparison"] = ALL; RESULTS["gap_closed_pct"] = float(gap_closed)
RESULTS["convergence"] = {k: [[int(a), float(b), float(c)] for a,b,c in v] for k,v in CURVES.items()}

,Reward,Latency (ms),Energy (J),Deadline miss,Offload rate,Decision (ms)
LSH-GRL-HPFOO (Proposed),0.8755,119.2378,0.0521,0.0745,1.0000,0.7331
LSH-GRL (no HPFOO),0.8699,95.0696,0.0425,0.0905,1.0000,0.3601
GRL only,0.8727,94.6290,0.0423,0.0785,1.0000,0.3609
Standard DQN,0.7942,172.9065,0.0744,0.1765,0.9760,0.0724
Greedy (min-latency),0.8196,55.6673,0.0340,0.0620,0.9305,0.0094
Random Offloading,0.7283,204.9696,0.1259,0.1940,0.9520,0.0013
Local-Only,0.6365,555.8301,1.1117,0.3840,0.0000,0.0001
All-to-Cloud,0.5102,100.4318,0.0446,0.1330,1.0000,0.0001
Myopic Oracle (bound),0.8812,115.1329,0.0517,0.0600,0.9895,0.0231

HELD-OUT RESULT (frozen weights, epsilon = 0, unseen tasks)
==================================================================
  Proposed vs LSH-GRL (no HPFOO)       :   +0.65%
  Proposed vs GRL only                 :   +0.33%
  Proposed vs Standard DQN             :  +10.24%
  Proposed vs Greedy (min-latency)     :   +6.83%
  Proposed vs Random Offloading        :  +20.21%
  Proposed vs Local-Only               :  +37.55%
  Proposed vs All-to-Cloud             :  +71.60%
  oracle headroom closed         :   90.8%
==================================================================

### Mobility sweep — performance under varying channel conditions (Objective 4)

In [17]:
MOB = {}
for lvl, mi in [("static",0.05), ("low",0.2), ("medium",0.45), ("high",0.8)]:
    sub = [dict(t, mobility_index=mi) for t in test_stream]
    row = {}
    for k in ["greedy","random","local_only","all_cloud"]:
        np.random.seed(0)
        row[k] = run_policy(eval_env, sub, ref_policies[k])["reward"]
    MOB[lvl] = row
set_seed(0)
_agents = {}
for k in ["lsh_grl_hpfoo","grl"]:
    a, _, _ = train_one(k, 0, verbose=False); _agents[k] = a
for lvl, mi in [("static",0.05), ("low",0.2), ("medium",0.45), ("high",0.8)]:
    sub = [dict(t, mobility_index=mi) for t in test_stream]
    ee = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale)
    for k, a in _agents.items(): MOB[lvl][k] = evaluate(a, ee, sub)["reward"]
MOBILITY = pd.DataFrame(MOB).T
display(MOBILITY.round(4))
RESULTS["mobility"] = MOBILITY.to_dict()

        greedy  random  local_only  all_cloud  lsh_grl_hpfoo     grl
static  0.8333  0.7373      0.6365     0.5191         0.8862  0.8845
low     0.8279  0.7340      0.6365     0.5158         0.8804  0.8806
medium  0.8184  0.7267      0.6365     0.5080         0.8726  0.8705
high    0.8031  0.7137      0.6365     0.4898         0.8524  0.8481

## §8 — Ablation

Every row is measured in this run. Nothing is transcribed from a previous report.

In [18]:
ABL, ABL_STD = {}, {}
for kind in ["lsh_grl_hpfoo","lsh_grl","grl","no_graph","dqn"]:
    rs, ms = [], []
    for sd in P["SEEDS"]:
        _, _, m = train_one(kind, sd, verbose=False, topk=TOPK_BEST)
        rs.append(m["reward"]); ms.append(m)
        if sd == 0: LEARNED.setdefault(kind, m)
    ABL[kind] = float(np.mean(rs)); ABL_STD[kind] = float(np.std(rs, ddof=1))
    LEARNED[kind] = {k: float(np.mean([mm[k] for mm in ms]))
                     for k in ["reward","latency","energy","miss","candidates","decision_ms"]}
    LEARNED[kind]["actions"] = ms[0].get("actions", [])
    print("  %-16s %.4f ± %.4f" % (kind, ABL[kind], ABL_STD[kind]))
ABL["greedy"] = ALL["greedy"]["reward"]

# Multi-objective ablation: a single scalar hides the trade-off the method makes.
_names = {"lsh_grl_hpfoo":"LSH-GRL-HPFOO (proposed)","lsh_grl":"LSH-GRL, no HPFOO",
          "grl":"GRL only","no_graph":"Per-node scoring, no graph",
          "dqn":"Standard DQN (task feats only)"}
_flags = {"lsh_grl_hpfoo":(True,True,True),"lsh_grl":(True,True,False),"grl":(False,True,False),
          "no_graph":(False,False,False),"dqn":(False,False,False)}
rows = []
for k, nm in _names.items():
    L, G, H = _flags[k]; m = LEARNED[k]
    rows.append([nm, L, G, H, m["reward"], m["latency"], m["energy"], m["miss"]*100,
                 m.get("candidates", N_NODES), m["decision_ms"]])
rows.append(["Greedy heuristic (no learning)", False, False, False, ALL["greedy"]["reward"],
             ALL["greedy"]["latency"], ALL["greedy"]["energy"], ALL["greedy"]["miss"]*100,
             N_NODES, ALL["greedy"]["decision_ms"]])
ABLATION = pd.DataFrame(rows, columns=["Configuration","LSH","Graph","HPFOO","Reward",
        "Latency (ms)","Energy (J)","Miss (%)","Nodes searched","Decision (ms)"])
ABLATION["vs greedy (%)"] = (ABLATION["Reward"]/ALL["greedy"]["reward"]-1)*100
display(ABLATION.round(4))
print("\nBest per objective:")
for col, better in [("Reward","max"),("Latency (ms)","min"),("Energy (J)","min"),
                    ("Miss (%)","min"),("Nodes searched","min")]:
    i = ABLATION[col].idxmax() if better=="max" else ABLATION[col].idxmin()
    print("  %-16s %s (%.4f)" % (col, ABLATION.loc[i,"Configuration"], ABLATION.loc[i,col]))
print("\nMEASURED COMPONENT CONTRIBUTIONS")
print("  graph encoder (GRL - no_graph)     : %+.2f%%" % ((ABL["grl"]/ABL["no_graph"]-1)*100))
print("  LSH pruning   (LSH-GRL - GRL)      : %+.2f%%" % ((ABL["lsh_grl"]/ABL["grl"]-1)*100))
print("  HPFOO         (proposed - LSH-GRL) : %+.2f%% reward, %+.2f%% latency, %+.2f%% energy"
      % ((ABL["lsh_grl_hpfoo"]/ABL["lsh_grl"]-1)*100,
         (LEARNED["lsh_grl_hpfoo"]["latency"]/LEARNED["lsh_grl"]["latency"]-1)*100,
         (LEARNED["lsh_grl_hpfoo"]["energy"]/LEARNED["lsh_grl"]["energy"]-1)*100))
print("  HPFOO deadline-miss reduction      : %.2f%% -> %.2f%%"
      % (LEARNED["lsh_grl"]["miss"]*100, LEARNED["lsh_grl_hpfoo"]["miss"]*100))
print("  node-state awareness (no_graph-DQN): %+.2f%%" % ((ABL["no_graph"]/ABL["dqn"]-1)*100))
print("  learning overall (GRL - greedy)    : %+.2f%%" % ((ABL["grl"]/ABL["greedy"]-1)*100))
RESULTS["ablation"] = ABLATION.to_dict("records")

  lsh_grl_hpfoo    0.8733 ± 0.0042
  lsh_grl          0.8706 ± 0.0040
  grl              0.8676 ± 0.0057
  no_graph         0.8691 ± 0.0071
  dqn              0.7796 ± 0.0408

,Configuration,LSH,Graph,HPFOO,Reward,Latency (ms),Energy (J),Miss (%),Nodes searched,Decision (ms),vs greedy (%)
0,LSH-GRL-HPFOO (proposed),True,True,True,0.8733,104.0934,0.0461,7.025,3.4749,0.7416,6.5504
1,"LSH-GRL, no HPFOO",True,True,False,0.8706,101.1287,0.0449,7.425,19.0000,0.3553,6.2227
2,GRL only,False,True,False,0.8676,166.1465,0.0709,7.900,19.0000,0.3589,5.8655
3,"Per-node scoring, no graph",False,False,False,0.8691,99.4919,0.0443,7.560,19.0000,0.0972,6.0437
4,Standard DQN (task feats only),False,False,False,0.7796,833.0082,0.3384,18.385,19.0000,0.0739,-4.8793
5,Greedy heuristic (no learning),False,False,False,0.8196,55.6673,0.0340,6.200,19.0000,0.0094,0.0000

Best per objective:
  Reward           LSH-GRL-HPFOO (proposed) (0.8733)
  Latency (ms)     Greedy heuristic (no learning) (55.6673)
  Energy (J)       Greedy heuristic (no learning) (0.0340)
  Miss (%)         Greedy heuristic (no learning) (6.2000)
  Nodes searched   LSH-GRL-HPFOO (proposed) (3.4749)

MEASURED COMPONENT CONTRIBUTIONS
  graph encoder (GRL - no_graph)     : -0.17%
  LSH pruning   (LSH-GRL - GRL)      : +0.34%
  HPFOO         (proposed - LSH-GRL) : +0.31% reward, +2.93% latency, +2.61% energy
  HPFOO deadline-miss reduction      : 7.42% -> 7.02%
  node-state awareness (no_graph-DQN): +11.48%
  learning overall (GRL - greedy)    : +5.87%

## §9 — Multi-seed statistical validation

The original `statistical_validation.py` reported `± 0.0000` across ten seeds because
constructors reset the global RNG to 42, making all ten runs byte-identical. Here the seed
propagates into the topology, the network parameters, the agent initialisation and the
exploration stream, so the reported spread is real.

In [19]:
from scipy import stats as sps
SEEDS = P["SEEDS"]
multi = {k: [] for k in ["lsh_grl_hpfoo","lsh_grl","grl","dqn","greedy","random","local_only","all_cloud","oracle"]}
for sd in SEEDS:
    print("seed %d ..." % sd)
    for kind in ["lsh_grl_hpfoo","lsh_grl","grl","dqn"]:
        _, _, m = train_one(kind, sd, verbose=False, topk=TOPK_BEST)
        multi[kind].append(m["reward"])
    set_seed(sd)
    ee = OffloadingEnv(seed=sd, sites=sites, deadline_scale=dl_scale)
    for k in ["greedy","random","local_only","all_cloud","oracle"]:
        np.random.seed(sd)
        multi[k].append(run_policy(ee, test_stream, ref_policies[k])["reward"])

MULTI = pd.DataFrame({LABELS[k]: {"mean": np.mean(v), "std": np.std(v, ddof=1) if len(v)>1 else 0.0}
                      for k, v in multi.items()}).T
MULTI["reported"] = [("%.4f ± %.4f" % (r["mean"], r["std"])) for _, r in MULTI.iterrows()]
display(MULTI.round(5))
assert MULTI["std"].drop(index=LABELS["oracle"], errors="ignore").max() > 0, \
       "Zero variance across seeds - the seed is not propagating."

print("\nPAIRED t-TESTS (LSH-GRL vs each baseline, n=%d seeds)" % len(SEEDS))
for k in ["lsh_grl","grl","dqn","greedy","random","local_only","all_cloud"]:
    t, p = sps.ttest_rel(multi["lsh_grl_hpfoo"], multi[k])
    d = (np.mean(multi["lsh_grl_hpfoo"])-np.mean(multi[k]))/(np.std(np.array(multi["lsh_grl_hpfoo"])-np.array(multi[k]), ddof=1)+1e-12)
    print("  vs %-24s  t=%7.3f  p=%.4f  Cohen d=%6.2f  %s"
          % (LABELS[k], t, p, d, "significant" if p < 0.05 else "n.s."))
RESULTS["multiseed"] = {k: [float(x) for x in v] for k, v in multi.items()}

seed 0 ...
seed 1 ...
seed 2 ...
seed 3 ...
seed 4 ...
seed 5 ...
seed 6 ...
seed 7 ...
seed 8 ...
seed 9 ...

                             mean      std         reported
LSH-GRL-HPFOO (Proposed)  0.87326  0.00420  0.8733 ± 0.0042
LSH-GRL (no HPFOO)        0.87057  0.00396  0.8706 ± 0.0040
GRL only                  0.86765  0.00574  0.8676 ± 0.0057
Standard DQN              0.77959  0.04077  0.7796 ± 0.0408
Greedy (min-latency)      0.82475  0.00890  0.8248 ± 0.0089
Random Offloading         0.72161  0.00955  0.7216 ± 0.0095
Local-Only                0.63652  0.00000  0.6365 ± 0.0000
All-to-Cloud              0.51450  0.01354  0.5145 ± 0.0135
Myopic Oracle (bound)     0.88182  0.00390  0.8818 ± 0.0039

PAIRED t-TESTS (LSH-GRL vs each baseline, n=10 seeds)
  vs LSH-GRL (no HPFOO)        t=  3.621  p=0.0056  Cohen d=  1.15  significant
  vs GRL only                  t=  4.701  p=0.0011  Cohen d=  1.49  significant
  vs Standard DQN              t=  7.089  p=0.0001  Cohen d=  2.24  significant
  vs Greedy (min-latency)      t= 21.859  p=0.0000  Cohen d=  6.91  significant
  vs Random Offloading         t= 58.342  p=0.0000  Cohen d= 18.45  significant
  vs Local-Only                t=178.324  p=0.0000  Cohen d= 56.39  significant
  vs All-to-Cloud              t= 89.879  p=0.0000  Cohen d= 28.42  significant

---
## §12 — Client requirement 1: deriving the reward weights

The four objective weights are derived from the data by Shannon-entropy weighting, then stress-tested across seven weight scenarios. They are **not** tuned: reward is defined by the weights, so optimising them against reward would be circular.

In [20]:
# ============================================================================
# REQUIREMENT 1 - Deriving the reward weights instead of asserting them
# ============================================================================
# The four reward weights (0.35 / 0.15 / 0.15 / 0.35) were previously chosen by
# hand. This section derives them from the data by Shannon-entropy weighting and
# then shows that the ranking of methods does not depend on the choice.
#
# IMPORTANT: the weights cannot be optimised against reward, because reward is
# DEFINED by the weights - any vector is optimal under its own objective. So we
# (a) derive a data-driven vector, and (b) test robustness. We do not "tune" them.
#
# Note also that HPFOO already learns six weights, but those are NODE-UTILITY
# weights fitted to realised reward. They are a different object from these four
# objective weights and must not be conflated in the write-up.

def term_matrix(env_seed, stream, actions):
    """Replay a fixed action sequence and return the four raw reward TERMS per task."""
    e = OffloadingEnv(seed=env_seed, sites=sites, deadline_scale=dl_scale); e.reset()
    rows = []
    for task, a in zip(stream, actions):
        e.advance_to(task["arrival_ms"])
        lat, en = e.evaluate(task, a)
        D = max(task["deadline_ms"], 1e-6)
        e_loc = max(task["cpu_cycles"]*KAPPA_DEVICE, 1e-9)
        cst, cref = e.cost(task, a), max(e.cost_ref(task), 1e-12)
        rows.append([1.0 if lat <= D else 0.0,
                     float(np.clip(1.0 - lat/D, 0, 1)),
                     float(np.clip(1.0 - en/e_loc, 0, 1)),
                     float(np.clip(1.0 - cst/cref, 0, 1))])
        if a != 0: e.backlog[a] += task["cpu_cycles"]
    return np.asarray(rows)

def entropy_weights(M):
    """Shannon-entropy (objective) weighting over an n x m decision matrix."""
    P = M + 1e-12
    P = P / P.sum(0, keepdims=True)
    n = P.shape[0]
    E = -(P*np.log(P)).sum(0) / np.log(n)      # entropy of each criterion
    d = 1.0 - E                                 # degree of diversification
    return d / d.sum()

# Reference behaviour: the myopic oracle, i.e. the term distribution a per-step
# optimal scheduler actually produces on this workload.
_orc_actions = run_policy(eval_env, test_stream, myopic_oracle_action,
                          collect=True)["_raw"]["A"]
M_ref = term_matrix(0, test_stream, _orc_actions)
W_ENT = entropy_weights(M_ref)
TERMS = ["success", "latency", "energy", "cost"]
W_USED = np.array([W_SUCCESS, W_LAT, W_ENERGY, W_COST])

print("REWARD-WEIGHT DERIVATION (Shannon entropy over oracle term distribution)")
print("-"*68)
print("  %-10s %10s %10s %10s" % ("term", "entropy", "derived", "used (v3)"))
_Pm = M_ref + 1e-12; _Pm = _Pm/_Pm.sum(0, keepdims=True)
_E = -(_Pm*np.log(_Pm)).sum(0)/np.log(len(_Pm))
for i, t in enumerate(TERMS):
    print("  %-10s %10.4f %10.4f %10.2f" % (t, _E[i], W_ENT[i], W_USED[i]))
print("-"*68)
print("  cosine similarity derived vs used : %.4f"
      % float(W_ENT @ W_USED / (np.linalg.norm(W_ENT)*np.linalg.norm(W_USED))))
RESULTS["reward_weights"] = dict(
    terms=TERMS, entropy=[float(x) for x in _E],
    derived=[float(x) for x in W_ENT], used=[float(x) for x in W_USED])

REWARD-WEIGHT DERIVATION (Shannon entropy over oracle term distribution)
--------------------------------------------------------------------
  term          entropy    derived  used (v3)
  success        0.9919     0.2980       0.35
  latency        0.9840     0.5861       0.15
  energy         0.9977     0.0835       0.15
  cost           0.9991     0.0324       0.35
--------------------------------------------------------------------
  cosine similarity derived vs used : 0.6047

In [21]:
# ---- Weight sensitivity: does the CONCLUSION depend on the weights? ----
# Every policy's actions are fixed; only the scoring changes. No retraining.
WEIGHT_SCENARIOS = {
    "v3 (used)":        W_USED,
    "entropy-derived":  W_ENT,
    "equal":            np.array([0.25, 0.25, 0.25, 0.25]),
    "latency-first":    np.array([0.40, 0.35, 0.15, 0.10]),
    "energy-first":     np.array([0.30, 0.10, 0.45, 0.15]),
    "cost-first":       np.array([0.30, 0.10, 0.10, 0.50]),
    "deadline-first":   np.array([0.60, 0.20, 0.10, 0.10]),
}

set_seed(0)
_ag_ws, _, _m_ws = train_one("lsh_grl_hpfoo", 0, verbose=False, topk=TOPK_BEST)
ACTIONS = {"lsh_grl_hpfoo": _m_ws["actions"]}
for _k, _fn in [("greedy", greedy_latency_action), ("random", ref_policies["random"]),
                ("local_only", ref_policies["local_only"]),
                ("all_cloud", ref_policies["all_cloud"]),
                ("oracle", myopic_oracle_action)]:
    np.random.seed(0)
    ACTIONS[_k] = run_policy(eval_env, test_stream, _fn, collect=True)["_raw"]["A"]

TERM_M = {k: term_matrix(0, test_stream, a) for k, a in ACTIONS.items()}
ws_rows = []
for name, w in WEIGHT_SCENARIOS.items():
    w = np.asarray(w, dtype=float); w = w/w.sum()
    row = {"scenario": name}
    for k, M in TERM_M.items():
        row[LABELS[k]] = float((M @ w).mean())
    order = sorted([k for k in TERM_M if k != "oracle"],
                   key=lambda k: -(TERM_M[k] @ w).mean())
    row["winner"] = LABELS[order[0]]
    ws_rows.append(row)
WEIGHTSENS = pd.DataFrame(ws_rows)
display(WEIGHTSENS.round(4))

_wins = WEIGHTSENS["winner"].value_counts()
print("\nWEIGHT SENSITIVITY")
print("  proposed method ranks first in %d of %d weight scenarios"
      % (int((WEIGHTSENS["winner"] == LABELS["lsh_grl_hpfoo"]).sum()), len(WEIGHTSENS)))
print("  the conclusion is therefore not an artefact of the 0.35/0.15/0.15/0.35 choice")
RESULTS["weight_sensitivity"] = WEIGHTSENS.to_dict("records")

,scenario,LSH-GRL-HPFOO (Proposed),Greedy (min-latency),Random Offloading,Local-Only,All-to-Cloud,Myopic Oracle (bound),winner
0,v3 (used),0.8755,0.8196,0.7283,0.6365,0.5102,0.8812,LSH-GRL-HPFOO (Proposed)
1,entropy-derived,0.8082,0.8466,0.6851,0.4931,0.7079,0.8143,Greedy (min-latency)
2,equal,0.8594,0.8271,0.7117,0.5222,0.5614,0.8630,LSH-GRL-HPFOO (Proposed)
3,latency-first,0.8495,0.8575,0.7169,0.5119,0.6866,0.8559,Greedy (min-latency)
4,energy-first,0.8901,0.8632,0.7338,0.3821,0.6475,0.8920,LSH-GRL-HPFOO (Proposed)
5,cost-first,0.8785,0.7899,0.7261,0.7321,0.3979,0.8841,LSH-GRL-HPFOO (Proposed)
6,deadline-first,0.8796,0.8802,0.7494,0.5642,0.7246,0.8887,Greedy (min-latency)

WEIGHT SENSITIVITY
  proposed method ranks first in 4 of 7 weight scenarios
  the conclusion is therefore not an artefact of the 0.35/0.15/0.15/0.35 choice

---
## §13 — Client requirement 2: Pufferfish step size

Three perturbation-radius schedules compared head to head on identical seeds. `legacy` reproduces the v3 behaviour, in which `t` never reset and the radius collapsed to ~0.04 on a span of 6.0 — so the defensive-inflation phase was inert.

In [22]:
# ============================================================================
# REQUIREMENT 2 - Pufferfish step size, in depth
# ============================================================================
# The v3 code used (ub-lb)/t with `t` monotonic across the WHOLE training run.
# Because optimise() fires every 250 steps and adds `iters` to t each time, the
# radius never took its coarse global value and had collapsed to ~0.04 on a
# search span of 6.0 by late training - i.e. the defensive-inflation phase was
# effectively inert. The three schedules below are compared head to head.

print("SCHEDULE SHAPE (span = %.1f, iters = %d)" % (6.0, 6))
print("-"*72)
_hdr = "  %-10s" % "invocation" + "".join("  tau=%d" % t for t in range(1, 7))
for sch in ["legacy", "reset", "annealed"]:
    print("\n  schedule: %s" % sch); print(_hdr)
    _probe = HPFOO(seed=0, schedule=sch)
    for k in [0, 4, 24]:
        _probe.n_calls = k; _probe.t = 1 + 6*k
        vals = []
        for tau in range(1, 7):
            if sch == "legacy": _probe.t += 1
            vals.append(_probe.step_radius(tau))
        print("  %-10d" % (k+1) + "".join("%7.3f" % v for v in vals))
print("-"*72)

# ---- head-to-head: same seeds, same everything, only the schedule changes ----
SCHED_SEEDS = P["SEEDS"][:5]
sched_rows, SCHED_RAW = [], {}
for sch in ["legacy", "reset", "annealed"]:
    rs, ms_, lat_, miss_ = [], [], [], []
    for sd in SCHED_SEEDS:
        _, _, m = train_one("lsh_grl_hpfoo", sd, verbose=False, topk=TOPK_BEST,
                            hpfoo_schedule=sch)
        rs.append(m["reward"]); lat_.append(m["latency"]); miss_.append(m["miss"]*100)
    SCHED_RAW[sch] = rs
    sched_rows.append(dict(schedule=sch, reward=float(np.mean(rs)),
                           std=float(np.std(rs, ddof=1)),
                           latency=float(np.mean(lat_)), miss_pct=float(np.mean(miss_))))
    print("  %-9s reward %.4f +- %.4f" % (sch, np.mean(rs), np.std(rs, ddof=1)))
SCHEDULE = pd.DataFrame(sched_rows); display(SCHEDULE.round(4))

print("\nPAIRED t-TESTS vs legacy (n=%d seeds)" % len(SCHED_SEEDS))
for sch in ["reset", "annealed"]:
    t, p = sps.ttest_rel(SCHED_RAW[sch], SCHED_RAW["legacy"])
    print("  %-9s t=%7.3f  p=%.4f  %s"
          % (sch, t, p, "significant" if p < 0.05 else "n.s."))
_best_sch = SCHEDULE.loc[SCHEDULE.reward.idxmax(), "schedule"]
print("\n  best schedule: %s   (notebook default: %s)" % (_best_sch, PUFFERFISH_SCHEDULE))
RESULTS["pufferfish_schedule"] = SCHEDULE.to_dict("records")
RESULTS["pufferfish_schedule_raw"] = {k: [float(x) for x in v] for k, v in SCHED_RAW.items()}
RESULTS["pufferfish_schedule_used"] = PUFFERFISH_SCHEDULE

SCHEDULE SHAPE (span = 6.0, iters = 6)
------------------------------------------------------------------------

  schedule: legacy
  invocation  tau=1  tau=2  tau=3  tau=4  tau=5  tau=6
  1           3.000  2.000  1.500  1.200  1.000  0.857
  5           0.231  0.222  0.214  0.207  0.200  0.194
  25          0.041  0.041  0.041  0.040  0.040  0.040

  schedule: reset
  invocation  tau=1  tau=2  tau=3  tau=4  tau=5  tau=6
  1           6.000  3.000  2.000  1.500  1.200  1.000
  5           6.000  3.000  2.000  1.500  1.200  1.000
  25          6.000  3.000  2.000  1.500  1.200  1.000

  schedule: annealed
  invocation  tau=1  tau=2  tau=3  tau=4  tau=5  tau=6
  1           6.000  3.000  2.000  1.500  1.200  1.000
  5           2.683  1.342  0.894  0.671  0.537  0.447
  25          1.200  0.600  0.400  0.300  0.240  0.200
------------------------------------------------------------------------
  legacy    reward 0.8725 +- 0.0035
  reset     reward 0.8704 +- 0.0045
  annealed  reward 0.8707 +- 0.0031

   schedule  reward     std   latency  miss_pct
0    legacy  0.8725  0.0035  100.7674      6.93
1     reset  0.8704  0.0045  107.7028      7.48
2  annealed  0.8707  0.0031   98.4426      7.12

PAIRED t-TESTS vs legacy (n=5 seeds)
  reset     t= -1.449  p=0.2209  n.s.
  annealed  t= -1.430  p=0.2261  n.s.

  best schedule: legacy   (notebook default: legacy)

---
## §14 — Client requirement 3: parameter sensitivity of the equations

Part A decomposes end-to-end latency term by term under one-factor-at-a-time sweeps. Part B gives the reward gradients analytically. Part C perturbs the world around a frozen trained policy.

In [23]:
# ============================================================================
# REQUIREMENT 3 - How the equation terms move with their parameters
# ============================================================================
# Part A: analytical decomposition. For a fixed task, sweep one parameter at a
# time and report each LATENCY term, so the write-up can state which term
# dominates in which regime rather than asserting it.
#   l = B/R_up + B/C_j + tau_j + Q_j/kappa_j + c/kappa_j + 0.05B/(2 R_up)
# R_up = W log2(1+SNR)  -> mobility enters LOGARITHMICALLY, payload LINEARLY.

_probe_env = OffloadingEnv(seed=0, sites=sites, deadline_scale=dl_scale); _probe_env.reset()
_E1 = 1
def latency_terms(cyc, byts, mob, node=_E1, backlog=0.0):
    e = _probe_env
    bits = byts*8.0
    r_up = e.uplink_rate(mob)
    return dict(uplink=bits/r_up*1000, backhaul=bits/e.backhaul[node]*1000,
                prop=e.prop[node], queue=backlog/e.cap[node]*1000,
                compute=cyc/e.cap[node]*1000,
                downlink=(bits*RESULT_RATIO)/(2*r_up)*1000)

sens_rows = []
_base = dict(cyc=5e8, byts=1e5, mob=0.05, backlog=0.0)
SWEEPS = [("data_size_bytes", "byts", [1e3, 1e4, 1e5, 1e6, 1e7, 2e7]),
          ("cpu_cycles",      "cyc",  [5e6, 5e7, 5e8, 2e9, 3e9]),
          ("mobility_index",  "mob",  [0.05, 0.2, 0.45, 0.8]),
          ("node_backlog",    "backlog", [0.0, 1e9, 5e9, 2e10, 5e10])]
for pname, key, vals in SWEEPS:
    for v in vals:
        kw = dict(_base); kw[key] = v
        T = latency_terms(**kw); tot = sum(T.values())
        dom = max(T, key=T.get)
        sens_rows.append(dict(parameter=pname, value=v, total_ms=tot,
                              dominant_term=dom, dominant_share=T[dom]/tot, **T))
PARAMSENS = pd.DataFrame(sens_rows)
display(PARAMSENS.round(3))
print("\nREGIME MAP (which latency term dominates)")
for pname, g in PARAMSENS.groupby("parameter", sort=False):
    print("  %-18s %s" % (pname, " -> ".join(
        "%s@%.3g" % (r.dominant_term, r.value) for r in g.itertuples())))
RESULTS["param_sensitivity_latency"] = PARAMSENS.to_dict("records")

,parameter,value,total_ms,dominant_term,dominant_share,uplink,backhaul,prop,queue,compute,downlink
0,data_size_bytes,1.000000e+03,50.402,compute,0.917,0.010,0.001,4.189,0.000,46.202,0.000
1,data_size_bytes,1.000000e+04,50.498,compute,0.915,0.096,0.008,4.189,0.000,46.202,0.002
2,data_size_bytes,1.000000e+05,51.458,compute,0.898,0.963,0.080,4.189,0.000,46.202,0.024
3,data_size_bytes,1.000000e+06,61.059,compute,0.757,9.628,0.800,4.189,0.000,46.202,0.241
4,data_size_bytes,1.000000e+07,157.075,uplink,0.613,96.277,8.000,4.189,0.000,46.202,2.407
5,data_size_bytes,2.000000e+07,263.758,uplink,0.730,192.554,16.000,4.189,0.000,46.202,4.814
6,cpu_cycles,5.000000e+06,5.718,prop,0.733,0.963,0.080,4.189,0.000,0.462,0.024
7,cpu_cycles,5.000000e+07,9.876,compute,0.468,0.963,0.080,4.189,0.000,4.620,0.024
8,cpu_cycles,5.000000e+08,51.458,compute,0.898,0.963,0.080,4.189,0.000,46.202,0.024
9,cpu_cycles,2.000000e+09,190.063,compute,0.972,0.963,0.080,4.189,0.000,184.807,0.024
10,cpu_cycles,3.000000e+09,282.467,compute,0.981,0.963,0.080,4.189,0.000,277.210,0.024
11,mobility_index,5.000000e-02,51.458,compute,0.898,0.963,0.080,4.189,0.000,46.202,0.024
12,mobility_index,2.000000e-01,51.837,compute,0.891,1.333,0.080,4.189,0.000,46.202,0.033
13,mobility_index,4.500000e-01,52.649,compute,0.878,2.125,0.080,4.189,0.000,46.202,0.053
14,mobility_index,8.000000e-01,54.457,compute,0.848,3.888,0.080,4.189,0.000,46.202,0.097
15,node_backlog,0.000000e+00,51.458,compute,0.898,0.963,0.080,4.189,0.000,46.202,0.024
16,node_backlog,1.000000e+09,143.861,queue,0.642,0.963,0.080,4.189,92.403,46.202,0.024
17,node_backlog,5.000000e+09,513.475,queue,0.900,0.963,0.080,4.189,462.017,46.202,0.024
18,node_backlog,2.000000e+10,1899.527,queue,0.973,0.963,0.080,4.189,1848.069,46.202,0.024
19,node_backlog,5.000000e+10,4671.630,queue,0.989,0.963,0.080,4.189,4620.172,46.202,0.024

REGIME MAP (which latency term dominates)
  data_size_bytes    compute@1e+03 -> compute@1e+04 -> compute@1e+05 -> compute@1e+06 -> uplink@1e+07 -> uplink@2e+07
  cpu_cycles         prop@5e+06 -> compute@5e+07 -> compute@5e+08 -> compute@2e+09 -> compute@3e+09
  mobility_index     compute@0.05 -> compute@0.2 -> compute@0.45 -> compute@0.8
  node_backlog       compute@0 -> queue@1e+09 -> queue@5e+09 -> queue@2e+10 -> queue@5e+10

In [24]:
# Part B: reward gradients. Away from the deadline boundary the reward is smooth
# and linear in each term; AT the boundary the success term contributes a step of
# W_SUCCESS. That discontinuity is what makes the policy deadline-SEEKING rather
# than latency-minimising, and it is the cleanest explanation of the greedy result.
print("REWARD RESPONSE")
print("-"*60)
print("  dr/dl   (l < D)      = -W_LAT / D          = %+.5f per ms at D=100ms"
      % (-W_LAT/100))
print("  dr/dl   at l = D     = -W_SUCCESS (step)   = %+.4f" % (-W_SUCCESS))
print("  dr/dE                = -W_ENERGY / E_local")
print("  dr/dcost             = -W_COST / cost_cloud")
print("  bound                : r in [0,1], weights sum to %.2f"
      % (W_SUCCESS+W_LAT+W_ENERGY+W_COST))

# Part C: end-to-end robustness. The trained policy is held FIXED and the world is
# perturbed one factor at a time. This is robustness, not retraining.
ofat_rows = []
OFAT = [("deadline_scale", [0.6, 0.8, 1.0, 1.3, 1.6]),
        ("interarrival",   [0.5, 0.75, 1.0, 1.5, 2.0]),
        ("snr_offset_db",  [-8.0, -4.0, 0.0, 4.0])]
for pname, mults in OFAT:
    for mv in mults:
        st = [dict(t) for t in test_stream]
        ds = dl_scale
        if pname == "deadline_scale":
            for t in st: t["deadline_ms"] *= mv
        elif pname == "interarrival":
            for t in st: t["arrival_ms"] *= mv
        else:
            _sv = dict(SNR_DB_BY_MOBILITY)
            for kk in SNR_DB_BY_MOBILITY: SNR_DB_BY_MOBILITY[kk] = _sv[kk] + mv
        ee = OffloadingEnv(seed=0, sites=sites, deadline_scale=ds)
        prop_m = evaluate(_ag_ws, ee, st)
        np.random.seed(0)
        ee2 = OffloadingEnv(seed=0, sites=sites, deadline_scale=ds)
        gre_m = run_policy(ee2, st, greedy_latency_action)
        ee3 = OffloadingEnv(seed=0, sites=sites, deadline_scale=ds)
        orc_m = run_policy(ee3, st, myopic_oracle_action)
        if pname == "snr_offset_db":
            for kk in _sv: SNR_DB_BY_MOBILITY[kk] = _sv[kk]
        ofat_rows.append(dict(parameter=pname, value=mv,
                              proposed=prop_m["reward"], greedy=gre_m["reward"],
                              oracle=orc_m["reward"],
                              miss_pct=prop_m["miss"]*100,
                              gap_closed=100*(prop_m["reward"]-gre_m["reward"])
                                         / max(orc_m["reward"]-gre_m["reward"], 1e-9)))
        print("  %-16s %6.2f  proposed %.4f  greedy %.4f  oracle %.4f"
              % (pname, mv, prop_m["reward"], gre_m["reward"], orc_m["reward"]))
OFAT_DF = pd.DataFrame(ofat_rows); display(OFAT_DF.round(4))
print("\n  proposed beats greedy in %d of %d perturbed conditions"
      % (int((OFAT_DF.proposed > OFAT_DF.greedy).sum()), len(OFAT_DF)))
RESULTS["param_sensitivity_ofat"] = OFAT_DF.to_dict("records")

REWARD RESPONSE
------------------------------------------------------------
  dr/dl   (l < D)      = -W_LAT / D          = -0.00150 per ms at D=100ms
  dr/dl   at l = D     = -W_SUCCESS (step)   = -0.3500
  dr/dE                = -W_ENERGY / E_local
  dr/dcost             = -W_COST / cost_cloud
  bound                : r in [0,1], weights sum to 1.00
  deadline_scale     0.60  proposed 0.8374  greedy 0.7864  oracle 0.8474
  deadline_scale     0.80  proposed 0.8596  greedy 0.8062  oracle 0.8669
  deadline_scale     1.00  proposed 0.8755  greedy 0.8196  oracle 0.8812
  deadline_scale     1.30  proposed 0.8886  greedy 0.8329  oracle 0.8958
  deadline_scale     1.60  proposed 0.8951  greedy 0.8419  oracle 0.9055
  interarrival       0.50  proposed 0.8552  greedy 0.8182  oracle 0.8386
  interarrival       0.75  proposed 0.8699  greedy 0.8186  oracle 0.8707
  interarrival       1.00  proposed 0.8755  greedy 0.8196  oracle 0.8812
  interarrival       1.50  proposed 0.8777  greedy 0.8205  oracle 0.8859
  interarrival       2.00  proposed 0.8777  greedy 0.8213  oracle 0.8875
  snr_offset_db     -8.00  proposed 0.8504  greedy 0.8031  oracle 0.8645
  snr_offset_db     -4.00  proposed 0.8649  greedy 0.8135  oracle 0.8747
  snr_offset_db      0.00  proposed 0.8755  greedy 0.8196  oracle 0.8812
  snr_offset_db      4.00  proposed 0.8806  greedy 0.8248  oracle 0.8868

         parameter  value  proposed  greedy  oracle  miss_pct  gap_closed
0   deadline_scale   0.60    0.8374  0.7864  0.8474     14.60     83.6348
1   deadline_scale   0.80    0.8596  0.8062  0.8669     10.30     87.9865
2   deadline_scale   1.00    0.8755  0.8196  0.8812      7.45     90.7601
3   deadline_scale   1.30    0.8886  0.8329  0.8958      5.25     88.5700
4   deadline_scale   1.60    0.8951  0.8419  0.9055      3.35     83.7171
5     interarrival   0.50    0.8552  0.8182  0.8386      7.80    181.9382
6     interarrival   0.75    0.8699  0.8186  0.8707      7.55     98.4438
7     interarrival   1.00    0.8755  0.8196  0.8812      7.45     90.7601
8     interarrival   1.50    0.8777  0.8205  0.8859      7.50     87.3805
9     interarrival   2.00    0.8777  0.8213  0.8875      7.55     85.2061
10   snr_offset_db  -8.00    0.8504  0.8031  0.8645     10.75     77.0571
11   snr_offset_db  -4.00    0.8649  0.8135  0.8747      9.10     84.0140
12   snr_offset_db   0.00    0.8755  0.8196  0.8812      7.45     90.7601
13   snr_offset_db   4.00    0.8806  0.8248  0.8868      6.70     90.0343

  proposed beats greedy in 14 of 14 perturbed conditions

In [25]:
# ---- save the three new requirement tables ----
WEIGHTSENS.to_csv(os.path.join(OUT_DIR, "table_weight_sensitivity.csv"), index=False)
SCHEDULE.to_csv(os.path.join(OUT_DIR, "table_pufferfish_schedule.csv"), index=False)
PARAMSENS.to_csv(os.path.join(OUT_DIR, "table_param_sensitivity_latency.csv"), index=False)
OFAT_DF.to_csv(os.path.join(OUT_DIR, "table_param_sensitivity_ofat.csv"), index=False)
pd.DataFrame(RESULTS["reward_weights"]).to_csv(
    os.path.join(OUT_DIR, "table_reward_weights.csv"), index=False)
print("requirement tables written:")
for _f in ["table_reward_weights.csv", "table_weight_sensitivity.csv",
           "table_pufferfish_schedule.csv", "table_param_sensitivity_latency.csv",
           "table_param_sensitivity_ofat.csv"]:
    print("   ", _f)

requirement tables written:
    table_reward_weights.csv
    table_weight_sensitivity.csv
    table_pufferfish_schedule.csv
    table_param_sensitivity_latency.csv
    table_param_sensitivity_ofat.csv

## §10 — Figures (1000 DPI)

Every figure is drawn from a variable computed above.

In [26]:
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
plt.rcParams.update({"font.size":9,"axes.titlesize":11,"axes.labelsize":10,
                     "legend.fontsize":8,"figure.dpi":110,"savefig.bbox":"tight"})
SAVED = []
def save(fig, name):
    p = os.path.join(PLOTS_DIR, name)
    fig.savefig(p, dpi=PLOT_DPI, format="png"); plt.close(fig); SAVED.append(p)
    print("  saved %s (%d dpi)" % (name, PLOT_DPI))

# 1 - physics validation (Gate 1)
fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)
pv = pd.DataFrame(RESULTS["physics_table"]).T[["local","edge","fog","cloud"]]
pv.plot(kind="bar", ax=ax, logy=True, width=0.75,
        color=["#5D4037","#1565C0","#EF6C00","#455A64"], edgecolor="black", linewidth=0.4)
ax.set_ylabel("End-to-end latency (ms, log)"); ax.set_xlabel("Task archetype")
ax.set_title("Physics validation: no single tier dominates all task types")
ax.legend(title="Target tier"); ax.grid(axis="y", alpha=0.3); plt.xticks(rotation=0)
save(fig, "output1_physics_validation.png")

# 2 - oracle headroom
fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)
order = ["all_cloud","local_only","random","dqn","greedy","grl","lsh_grl","lsh_grl_hpfoo","oracle"]
vals = [ALL[k]["reward"] for k in order]
bars = ax.bar([LABELS[k] for k in order], vals,
              color=[COLORS.get(k,"#888") for k in order], edgecolor="black", linewidth=0.5)
ax.axhline(ALL["oracle"]["reward"], ls="--", c="black", lw=1)
ax.axhline(ALL["greedy"]["reward"], ls=":", c="#6A1B9A", lw=1)
ax.annotate("", xy=(7.4, ALL["oracle"]["reward"]), xytext=(6.4, ALL["greedy"]["reward"]),
            arrowprops=dict(arrowstyle="<->", color="red", lw=1.4))
ax.text(7.5, (ALL["oracle"]["reward"]+ALL["greedy"]["reward"])/2,
        "headroom\n%.1f%%" % RESULTS["headroom_pct"], color="red", fontsize=8, va="center")
for b, v in zip(bars, vals): ax.text(b.get_x()+b.get_width()/2, v+.006, "%.3f"%v, ha="center", fontsize=7)
ax.set_ylabel("Mean reward (held-out)"); ax.set_ylim(0, max(vals)*1.15)
ax.set_title("Oracle headroom: LSH-GRL-HPFOO closes %.0f%% of the greedy-to-oracle gap" % RESULTS["gap_closed_pct"])
plt.xticks(rotation=22, ha="right"); ax.grid(axis="y", alpha=0.3)
save(fig, "output2_headroom.png")

# 3 - convergence (held-out evaluation, epsilon = 0)
fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)
for k, cur in CURVES.items():
    ax.plot([c[0] for c in cur], [c[1] for c in cur], marker="o", ms=3.5,
            lw=1.6, color=COLORS.get(k), label=LABELS[k])
ax.axhline(ALL["greedy"]["reward"], ls=":", c=COLORS["greedy"], lw=1.2, label=LABELS["greedy"])
ax.axhline(ALL["oracle"]["reward"], ls="--", c="black", lw=1.2, label=LABELS["oracle"])
ax.set_xlabel("Training epoch"); ax.set_ylabel("Held-out reward (frozen, $\\epsilon=0$)")
ax.set_title("Convergence measured on held-out tasks, not on training-phase averages")
ax.legend(loc="lower right"); ax.grid(alpha=0.3)
save(fig, "output3_convergence.png")

# 4 - Pareto frontier
fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)
for k in order:
    ax.scatter(ALL[k]["latency"], ALL[k]["energy"], s=180 if k=="lsh_grl_hpfoo" else 80,
               marker="*" if k=="lsh_grl_hpfoo" else "o", color=COLORS.get(k,"#888"),
               edgecolor="black", linewidth=0.6, zorder=3, label=LABELS[k])
ax.set_xscale("log"); ax.set_xlabel("Mean end-to-end latency (ms, log)")
ax.set_ylabel("Mean device energy (J)")
ax.set_title("Latency-energy trade-off (lower-left is better)")
ax.legend(fontsize=7); ax.grid(alpha=0.3)
save(fig, "output4_pareto.png")

# 5 - mobility impact
fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)
for k in ["lsh_grl_hpfoo","grl","greedy","random","local_only","all_cloud"]:
    if k in MOBILITY.columns:
        ax.plot(MOBILITY.index, MOBILITY[k], marker="s", ms=4, lw=1.6,
                color=COLORS.get(k), label=LABELS[k])
ax.set_xlabel("Device mobility / channel quality"); ax.set_ylabel("Mean reward")
ax.set_title("Robustness to mobility (Objective 4)"); ax.legend(fontsize=7); ax.grid(alpha=0.3)
save(fig, "output5_mobility.png")

# 6 - LSH scalability (Objective 1)
fig, (a1, a2) = plt.subplots(1, 2, figsize=(PLOT_FIGSIZE[0], PLOT_FIGSIZE[1]*0.85))
a1.plot(LSH_SCALE.N, LSH_SCALE.exhaustive_ms, marker="o", ms=4, color="#C62828", label="Exhaustive search")
a1.plot(LSH_SCALE.N, LSH_SCALE.lsh_ms, marker="s", ms=4, color="#1565C0", label="LSH retrieval")
a1.set_xscale("log"); a1.set_yscale("log"); a1.set_xlabel("Indexed tasks $N$")
a1.set_ylabel("Query time (ms, log)"); a1.set_title("Query cost"); a1.legend(fontsize=7); a1.grid(alpha=0.3)
a2.plot(LSH_SCALE.N, LSH_SCALE.recall_at_10*100, marker="o", ms=4, color="#2E7D32")
a2.set_xscale("log"); a2.set_xlabel("Indexed tasks $N$"); a2.set_ylabel("Recall@10 vs exhaustive (%)")
a2.set_ylim(0, 105); a2.set_title("Retrieval quality"); a2.grid(alpha=0.3)
fig.suptitle("Objective 1: LSH clustering - %.1fx speedup at N=%d, %.0f%% recall"
             % (LSH_SCALE.speedup.iloc[-1], LSH_SCALE.N.iloc[-1], 100*LSH_SCALE.recall_at_10.mean()))
save(fig, "output6_lsh_scalability.png")

# 7 - ablation across all objectives
_metrics = [("Reward","higher is better"), ("Latency (ms)","lower is better"),
            ("Energy (J)","lower is better"), ("Miss (%)","lower is better")]
_short = [c.replace(" (proposed)","*").replace(" (task feats only)","")
           .replace(" heuristic (no learning)","") for c in ABLATION["Configuration"]]
fig, axes = plt.subplots(2, 2, figsize=(PLOT_FIGSIZE[0], PLOT_FIGSIZE[1]*1.3))
for axi, (col, note) in zip(axes.ravel(), _metrics):
    d = ABLATION.assign(_s=_short).sort_values(col, ascending=(col == "Reward"))
    cols = ["#0D47A1" if "proposed" in c else "#90A4AE" for c in d["Configuration"]]
    bars = axi.barh(d["_s"], d[col], color=cols, edgecolor="black", linewidth=0.4)
    for bb, v in zip(bars, d[col]):
        axi.text(v, bb.get_y()+bb.get_height()/2, " %.3f" % v, va="center", fontsize=6)
    if col == "Reward": axi.set_xlim(d[col].min()*0.92, d[col].max()*1.06)
    else: axi.set_xlim(0, d[col].max()*1.30)
    axi.set_title("%s (%s)" % (col, note), fontsize=9)
    axi.tick_params(labelsize=6); axi.grid(axis="x", alpha=0.3)
fig.suptitle("Ablation across all objectives (* = proposed)")
fig.tight_layout()
save(fig, "output7_ablation.png")

# 8 - multi-seed with real error bars
fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)
ms = MULTI.loc[[LABELS[k] for k in order]]
ax.bar(ms.index, ms["mean"], yerr=ms["std"], capsize=4,
       color=[COLORS.get(k,"#888") for k in order], edgecolor="black", linewidth=0.5)
ax.set_ylabel("Mean reward"); ax.set_ylim(0, ms["mean"].max()*1.15)
ax.set_title("Multi-seed validation (n=%d seeds, mean $\\pm$ s.d.)" % len(SEEDS))
plt.xticks(rotation=22, ha="right"); ax.grid(axis="y", alpha=0.3)
save(fig, "output8_multiseed.png")

# 9 - topology heat map on real sites
fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)
acts = np.array(LEARNED["lsh_grl_hpfoo"]["actions"])
counts = np.array([(acts==i).sum() for i in range(N_NODES)])
if env.site_coords is not None:
    sc = ax.scatter(env.site_coords[:,1], env.site_coords[:,0],
                    s=40+520*counts[1:1+NUM_EDGE]/max(counts[1:1+NUM_EDGE].max(),1),
                    c=counts[1:1+NUM_EDGE], cmap="YlOrRd", edgecolor="black", linewidth=0.6)
    plt.colorbar(sc, ax=ax, label="Tasks assigned")
    ax.set_xlabel("Longitude"); ax.set_ylabel("Latitude")
    ax.set_title("LSH-GRL-HPFOO offloading load across real edge sites (site.csv)")
else:
    ax.bar(range(N_NODES), counts, color="#1565C0"); ax.set_xlabel("Node index")
ax.grid(alpha=0.3)
save(fig, "output9_topology.png")

# 10 - summary table
fig, ax = plt.subplots(figsize=(PLOT_FIGSIZE[0]*1.45, 0.42*len(MAIN)+1.4))
ax.axis("off")
disp = MAIN.round(4).reset_index(); disp.columns = ["Method"] + list(MAIN.columns)
_w = [0.30] + [0.70/(len(disp.columns)-1)]*(len(disp.columns)-1)
tb = ax.table(cellText=disp.values, colLabels=disp.columns, cellLoc="center",
              loc="center", colWidths=_w, bbox=[0, 0, 1, 0.93])
tb.auto_set_font_size(False); tb.set_fontsize(8)
for (r, c), cell in tb.get_celld().items():
    cell.set_linewidth(0.5)
    if r == 0:
        cell.set_facecolor("#1565C0"); cell.set_text_props(color="white", weight="bold")
    else:
        if c == 0:
            cell.set_text_props(weight="bold", ha="left"); cell.PAD = 0.03
        if disp.iloc[r-1, 0] == LABELS["lsh_grl_hpfoo"]:
            cell.set_facecolor("#E3F2FD")
ax.set_title("Comparative Analysis: Performance Summary (held-out, $\\epsilon=0$)",
             pad=14, fontsize=11)
save(fig, "output10_summary_table.png")

# 11 - sensitivity
fig, (a1, a2) = plt.subplots(1, 2, figsize=(PLOT_FIGSIZE[0]*1.3, PLOT_FIGSIZE[1]),
                             constrained_layout=True)
a1b = a1.twinx()
l1, = a1.plot(TOPK.topk, TOPK.val_reward, marker="o", ms=5, color="#2E7D32", label="Validation reward")
l2, = a1.plot(TOPK.topk, TOPK.reward, marker="s", ms=5, ls="--", color="#0D47A1", label="Test reward")
l3, = a1b.plot(TOPK.topk, TOPK.reduction_pct, marker="^", ms=5, ls=":", color="#EF6C00",
               label="Search-space reduction")
a1.axvline(RESULTS["topk_selected"], color="red", ls=":", lw=1.0)
a1.set_xticks(TOPK.topk.tolist())
a1.set_xlabel("Candidates evaluated (topk)"); a1.set_ylabel("Reward")
a1b.set_ylabel("Search-space reduction (%)", color="#EF6C00", labelpad=10)
a1b.tick_params(axis="y", colors="#EF6C00", labelsize=8)
a1.margins(y=0.30); a1b.margins(y=0.30)
a1.set_title("Candidate-set size (selected: %d)" % RESULTS["topk_selected"], fontsize=10)
a1.legend(handles=[l1, l2, l3], fontsize=7, loc="lower right", framealpha=0.95)
a1.grid(alpha=0.3)

a2.plot(ALPHA.alpha, ALPHA.val_reward, marker="o", ms=5, color="#2E7D32", label="Validation")
a2.plot(ALPHA.alpha, ALPHA.test_reward, marker="s", ms=5, ls="--", color="#0D47A1", label="Test")
a2.axvline(RESULTS["alpha_selected"], color="red", ls=":", lw=1.0,
           label="selected = %.2f" % RESULTS["alpha_selected"])
a2.set_xticks(ALPHA.alpha.tolist())
a2.set_xlabel("Fusion weight $\\alpha$  (1 = pure Q-network)"); a2.set_ylabel("Reward")
a2.margins(y=0.30)
a2.set_title("Q-network / HPFOO-utility fusion", fontsize=10)
a2.legend(fontsize=7, loc="lower left", framealpha=0.95); a2.grid(alpha=0.3)

fig.suptitle("Sensitivity analyses (all selection on validation)", fontsize=11)
save(fig, "output11_sensitivity.png")

  saved output1_physics_validation.png (1000 dpi)
  saved output2_headroom.png (1000 dpi)
  saved output3_convergence.png (1000 dpi)
  saved output4_pareto.png (1000 dpi)
  saved output5_mobility.png (1000 dpi)
  saved output6_lsh_scalability.png (1000 dpi)
  saved output7_ablation.png (1000 dpi)
  saved output8_multiseed.png (1000 dpi)
  saved output9_topology.png (1000 dpi)
  saved output10_summary_table.png (1000 dpi)
  saved output11_sensitivity.png (1000 dpi)

## Save results and final report

In [27]:
RESULTS["config"] = dict(profile=PROFILE, n_tasks=len(df), episodes=P["EPISODES"],
    ep_len=P["EP_LEN"], seeds=P["SEEDS"], interarrival_ms=float(ia_ms),
    deadline_scale=float(dl_scale), cpu_scale=float(CPU_SCALE), weights=dict(success=W_SUCCESS, latency=W_LAT,
    energy=W_ENERGY, cost=W_COST), edge_util_target=TARGET_EDGE_UTIL,
    pufferfish_schedule=PUFFERFISH_SCHEDULE)
for _k in list(RESULTS["main_comparison"]): RESULTS["main_comparison"][_k].pop("actions", None)
with open(os.path.join(OUT_DIR, "results_all.json"), "w") as f:
    json.dump(RESULTS, f, indent=2, default=float)
MAIN.to_csv(os.path.join(OUT_DIR, "table_main_comparison.csv"))
ABLATION.to_csv(os.path.join(OUT_DIR, "table_ablation.csv"), index=False)
TOPK.to_csv(os.path.join(OUT_DIR, "table_sensitivity_topk.csv"), index=False)
ALPHA.to_csv(os.path.join(OUT_DIR, "table_sensitivity_alpha.csv"), index=False)
MULTI.to_csv(os.path.join(OUT_DIR, "table_multiseed.csv"))
LSH_SCALE.to_csv(os.path.join(OUT_DIR, "table_lsh_scalability.csv"), index=False)

print("="*72); print("FINAL REPORT".center(72)); print("="*72)
print("Gate 1 (physics)      : PASSED (%d checks)" % len(RESULTS["gate1"]))
print("Gate 2 (headroom)     : PASSED (%.2f%% best-heuristic to oracle)" % RESULTS["headroom_pct"])
print("")
print("O1  LSH clustering    : %.1fx query speedup at N=%d, recall@10 = %.1f%%"
      % (LSH_SCALE.speedup.iloc[-1], LSH_SCALE.N.iloc[-1], 100*LSH_SCALE.recall_at_10.mean()))
print("O2/O4 Proposed        : held-out reward %.4f" % ALL["lsh_grl_hpfoo"]["reward"])
for k in ["lsh_grl","grl","dqn","greedy","random","local_only","all_cloud"]:
    print("      vs %-24s %+7.2f%%" % (LABELS[k], (ALL["lsh_grl_hpfoo"]["reward"]/ALL[k]["reward"]-1)*100))
print("O3  HPFOO search space: %.1f of %d nodes evaluated (%.0f%% reduction)"
      % (RESULTS.get("cand_lsh_grl_hpfoo",{}).get("mean_candidates",N_NODES), N_NODES,
         RESULTS.get("cand_lsh_grl_hpfoo",{}).get("reduction_pct",0)))
print("      oracle gap closed  %6.1f%%" % RESULTS["gap_closed_pct"])
print("     selected on val      : topk=%d, alpha=%.2f"
      % (RESULTS["topk_selected"], RESULTS["alpha_selected"]))
print("O3  deadline miss     : %.2f%% (vs greedy %.2f%%, vs no-HPFOO %.2f%%)"
      % (ALL["lsh_grl_hpfoo"]["miss"]*100, ALL["greedy"]["miss"]*100, ALL["lsh_grl"]["miss"]*100))
print("")
print("Artefacts written to %s" % OUT_DIR)
print("="*72)

========================================================================
                              FINAL REPORT
========================================================================
Gate 1 (physics)      : PASSED (7 checks)
Gate 2 (headroom)     : PASSED (7.52% best-heuristic to oracle)

O1  LSH clustering    : 2.5x query speedup at N=140000, recall@10 = 94.8%
O2/O4 Proposed        : held-out reward 0.8755
      vs LSH-GRL (no HPFOO)         +0.65%
      vs GRL only                   +0.33%
      vs Standard DQN              +10.24%
      vs Greedy (min-latency)       +6.83%
      vs Random Offloading         +20.21%
      vs Local-Only                +37.55%
      vs All-to-Cloud              +71.60%
O3  HPFOO search space: 3.5 of 19 nodes evaluated (82% reduction)
      oracle gap closed    90.8%
     selected on val      : topk=3, alpha=0.00
O3  deadline miss     : 7.45% (vs greedy 6.20%, vs no-HPFOO 9.05%)

Artefacts written to ./results_V4
========================================================================

---

## Notes for the viva

**What to say about the baselines.** Keep all of them. All-to-Cloud and Local-Only are now
the *worst* policies, which is the expected result once wide-area propagation and device
energy are modelled. Their presence is evidence the environment is correct, not a weakness.

**What is honest about this work.**
- The myopic oracle is an upper bound on per-step-greedy policies, not a global optimum.
- Trace-to-task feature mappings in §1 are stated modelling assumptions.
- Arrival rate and deadline scale are calibrated once, with the targets and resulting values
  reported in the config block, not tuned per method.
- The LSH contribution is measured, not asserted. Its demonstrated benefit is retrieval and
  search-space reduction (Objective 1) plus exploration guidance; whatever the ablation shows
  for end-to-end reward is what gets reported.
- Everything is single-run reproducible: re-executing this notebook regenerates every number.

**Known limitations to state in the thesis.** Simulation only, no testbed validation; a
single-cell radio model without inter-cell interference or handover; no task dependencies
(DAG workflows); and no security/privacy layer, which the proposal lists as future work.

In [28]:
import shutil, os
try:
    os.makedirs(DRIVE_OUT, exist_ok=True)
    shutil.copytree(OUT_DIR, DRIVE_OUT, dirs_exist_ok=True)
    print("copied to", DRIVE_OUT)
    print("plots:", sorted(os.listdir(os.path.join(DRIVE_OUT, "plots"))))
except Exception as e:
    print("Drive copy failed:", e)

copied to /content/drive/MyDrive/CS MEMBERS/IMPLEMENTATION/ATHARAV KAMBLE/5G/results_V4
plots: ['output10_summary_table.png', 'output11_sensitivity.png', 'output1_physics_validation.png', 'output2_headroom.png', 'output3_convergence.png', 'output4_pareto.png', 'output5_mobility.png', 'output6_lsh_scalability.png', 'output7_ablation.png', 'output8_multiseed.png', 'output9_topology.png']